import type { GlossaryEntry } from "./glossary";

/** Terms per interview series (key = series slug). Filled in alongside the lessons. */
export const IV_TERMS: Record<string, GlossaryEntry[]> = {
  browser: [
    // ── Network ────────────────────────────────────────────────────────────
    { term: "DNS", full: "Domain Name System", desc: "The internet's phone book: turns a name like react.dev into an IP address. Answers are cached according to a TTL.", lesson: 0, group: "Network" },
    { term: "TCP", full: "Transmission Control Protocol", desc: "The reliable, ordered connection underneath HTTP/1.1 and HTTP/2. Opening one costs a three-way handshake, one round trip.", lesson: 0, group: "Network" },
    { term: "QUIC", full: "QUIC", desc: "The UDP-based transport under HTTP/3. It merges the transport and TLS handshakes and avoids TCP's head-of-line blocking.", lesson: 0, group: "Network" },
    { term: "TLS", full: "Transport Layer Security", desc: "The encryption layer behind HTTPS. The browser checks the server's certificate and both sides agree on session keys.", lesson: 0, group: "Network" },
    { term: "RTT", full: "Round-trip time", desc: "How long a packet takes to reach the server and come back. Every handshake costs at least one RTT, which is why distance matters.", lesson: 0, group: "Network" },
    { term: "TTL", full: "Time to live", desc: "How long a DNS answer may be cached before it must be looked up again.", lesson: 0, group: "Network" },
    { term: "CDN", full: "Content Delivery Network", desc: "Servers around the world that keep copies of your files close to users, cutting distance and load on your origin.", lesson: 5, group: "Network" },
    { term: "HSTS", full: "HTTP Strict Transport Security", desc: "A header telling the browser to use HTTPS only for this site, so it never sends an insecure first request.", lesson: 0, group: "Network" },
    { term: "bfcache", full: "Back/forward cache", desc: "Lets the browser restore an entire page, JavaScript state included, from memory when you press Back or Forward.", lesson: 0, group: "Network" },
    // ── HTTP ───────────────────────────────────────────────────────────────
    { term: "CORS", full: "Cross-Origin Resource Sharing", desc: "Headers with which a server lets other origins read its responses. Enforced by browsers only; it is not a firewall.", lesson: 4, group: "HTTP" },
    { term: "preflight", aliases: ["Preflight"], full: "CORS preflight", desc: "An OPTIONS request the browser sends first to ask whether a cross-origin request with a given method or headers is allowed.", lesson: 4, group: "HTTP" },
    { term: "ETag", full: "Entity tag", desc: "A fingerprint of a response. The browser sends it back in If-None-Match so the server can answer 304 Not Modified instead of resending the body.", lesson: 5, group: "HTTP" },
    { term: "idempotent", aliases: ["Idempotent", "idempotency"], full: "Idempotent", desc: "Doing it once or many times leaves the server in the same state, so it is safe to retry. PUT and DELETE are; POST is not.", lesson: 6, group: "HTTP" },
    { term: "Origin", full: "Origin", desc: "Scheme + host + port. Two URLs are same-origin only if all three match; the same-origin policy is built on it.", lesson: 4, group: "HTTP" },
    { term: "TTFB", full: "Time to First Byte", desc: "Time from sending the request to receiving the first byte of the response: network time plus all server work.", lesson: 0, group: "HTTP" },
    // ── Storage and auth ───────────────────────────────────────────────────
    { term: "HttpOnly", full: "HttpOnly cookie attribute", desc: "Hides the cookie from JavaScript, so an XSS payload cannot read it. It cannot stop the payload from using the session.", lesson: 1, group: "Storage and auth" },
    { term: "SameSite", full: "SameSite cookie attribute", desc: "Strict, Lax or None: whether the cookie is sent on cross-site requests. The main built-in CSRF defence.", lesson: 1, group: "Storage and auth" },
    { term: "IndexedDB", full: "IndexedDB", desc: "An asynchronous, transactional database in the browser for large or structured data, usable from workers.", lesson: 1, group: "Storage and auth" },
    { term: "JWT", full: "JSON Web Token", desc: "A signed token of three base64url parts (header.payload.signature). Readable by anyone who holds it; the signature proves it was not altered.", lesson: 2, group: "Storage and auth" },
    { term: "JWKS", full: "JSON Web Key Set", desc: "A published list of public keys that services use to verify tokens signed with a private key.", lesson: 2, group: "Storage and auth" },
    { term: "refresh token", aliases: ["Refresh token", "refresh tokens"], full: "Refresh token", desc: "A longer-lived credential used only to get new short-lived access tokens, ideally rotated on every use.", lesson: 2, group: "Storage and auth" },
    { term: "BFF", full: "Backend for Frontend", desc: "A server you own between the browser and downstream APIs. It holds the tokens so the browser only ever has a session cookie.", lesson: 3, group: "Storage and auth" },
    // ── Security ───────────────────────────────────────────────────────────
    { term: "XSS", full: "Cross-Site Scripting", desc: "An attacker gets their JavaScript to run on your origin, so it can read storage and act as the user.", lesson: 3, group: "Security" },
    { term: "CSRF", full: "Cross-Site Request Forgery", desc: "Another site makes the victim's browser send a request to yours, and the browser attaches the cookies automatically.", lesson: 3, group: "Security" },
    { term: "CSP", full: "Content Security Policy", desc: "A response header listing which sources of scripts, styles and frames the browser may use. A backstop if escaping fails.", lesson: 7, group: "Security" },
    { term: "SRI", full: "Subresource Integrity", desc: "An integrity hash on a script or stylesheet tag. The browser refuses the file if its content does not match.", lesson: 7, group: "Security" },
    { term: "nonce", aliases: ["Nonce"], full: "Nonce", desc: "A random one-time value generated per response and used to mark which inline scripts a CSP allows.", lesson: 7, group: "Security" },
    { term: "clickjacking", aliases: ["Clickjacking"], full: "Clickjacking", desc: "Framing your site invisibly on another page to trick users into clicking your buttons. Stopped by frame-ancestors.", lesson: 7, group: "Security" },
    // ── Rendering and performance ──────────────────────────────────────────
    { term: "DOM", full: "Document Object Model", desc: "The tree of elements the browser builds from your HTML. JavaScript reads and changes the page through it.", lesson: 0, group: "Rendering and performance" },
    { term: "CSSOM", full: "CSS Object Model", desc: "The browser's tree of styles. Painting waits for it, which is why CSS blocks rendering.", lesson: 0, group: "Rendering and performance" },
    { term: "hydration", aliases: ["Hydration"], full: "Hydration", desc: "React re-running on the client over server-rendered HTML to attach event handlers. Until it finishes, buttons look ready but do nothing.", lesson: 0, group: "Rendering and performance" },
    { term: "reflow", aliases: ["Reflow"], full: "Reflow (layout)", desc: "Recalculating the size and position of elements. Expensive, and triggered by changing width, height, margin and similar.", lesson: 8, group: "Rendering and performance" },
    { term: "layout thrashing", aliases: ["Layout thrashing"], full: "Layout thrashing", desc: "Alternating layout reads and style writes in a loop so the browser recalculates layout every iteration.", lesson: 8, group: "Rendering and performance" },
    { term: "long task", aliases: ["long tasks", "Long task"], full: "Long task", desc: "Any task that holds the main thread for more than 50 ms, delaying input and painting.", lesson: 8, group: "Rendering and performance" },
    { term: "LCP", full: "Largest Contentful Paint", desc: "When the largest visible element (usually the hero image or heading) is painted. Good is 2.5 s or less.", lesson: 9, group: "Rendering and performance" },
    { term: "INP", full: "Interaction to Next Paint", desc: "How long the page takes to visually respond to clicks, taps and keys, across the whole visit. Good is 200 ms or less. Replaced FID in 2024.", lesson: 9, group: "Rendering and performance" },
    { term: "CLS", full: "Cumulative Layout Shift", desc: "A score for how much visible content jumps around unexpectedly. Good is 0.1 or less.", lesson: 9, group: "Rendering and performance" },
    { term: "FID", full: "First Input Delay", desc: "The old responsiveness metric: only the delay before the first interaction was handled. Replaced by INP.", lesson: 9, group: "Rendering and performance" },
    { term: "FCP", full: "First Contentful Paint", desc: "When the first text or image appears on screen.", lesson: 0, group: "Rendering and performance" },
    { term: "TBT", full: "Total Blocking Time", desc: "A lab metric: the total time the main thread was blocked by long tasks. Used as a proxy for INP in Lighthouse.", lesson: 9, group: "Rendering and performance" },
    { term: "CrUX", full: "Chrome UX Report", desc: "Google's dataset of real-user performance measurements, used by PageSpeed Insights and Search Console.", lesson: 9, group: "Rendering and performance" },
    { term: "RUM", full: "Real User Monitoring", desc: "Measuring performance from real visitors' browsers rather than in a lab test.", lesson: 9, group: "Rendering and performance" },
  ],
  backend: [
    // ── Design ─────────────────────────────────────────────────────────────
    { term: "SOLID", full: "SOLID principles", desc: "Five design principles: single responsibility, open/closed, Liskov substitution, interface segregation and dependency inversion.", lesson: 0, group: "Design" },
    { term: "DRY", full: "Don't Repeat Yourself", desc: "Keep one source of truth for each piece of knowledge. It is about shared rules, not identical-looking text.", lesson: 0, group: "Design" },
    { term: "DTO", full: "Data Transfer Object", desc: "A plain object that defines the shape of data crossing a boundary, such as a request body or response, separate from the database model.", lesson: 3, group: "Design" },
    { term: "dependency injection", aliases: ["Dependency injection"], full: "Dependency injection", desc: "Passing a function the things it needs (repository, clock, gateway) instead of letting it import or create them.", lesson: 0, group: "Design" },
    { term: "controller", aliases: ["controllers"], full: "Controller", desc: "The layer that translates HTTP to a service call and back: reads the request, calls one service function, shapes the response.", lesson: 1, group: "Design" },
    { term: "repository", aliases: ["repositories"], full: "Repository", desc: "The layer that owns data access. Only it knows about the ORM or SQL.", lesson: 1, group: "Design" },
    // ── API ────────────────────────────────────────────────────────────────
    { term: "REST", full: "Representational State Transfer", desc: "An API style built on resources (nouns) identified by URLs and manipulated with HTTP methods and status codes.", lesson: 2, group: "API" },
    { term: "OpenAPI", full: "OpenAPI Specification", desc: "A machine-readable description of a REST API, used for docs, generated types and breaking-change checks.", lesson: 2, group: "API" },
    { term: "idempotency key", aliases: ["Idempotency-Key", "idempotency keys"], full: "Idempotency key", desc: "A unique value the client sends with a POST so the server can detect a retry and return the first result instead of repeating the work.", lesson: 2, group: "API" },
    { term: "problem details", aliases: ["Problem Details"], full: "Problem Details for HTTP APIs", desc: "A standard JSON error format (type, title, status, detail) served as application/problem+json.", lesson: 2, group: "API" },
    { term: "mass assignment", aliases: ["over-posting"], full: "Mass assignment", desc: "A bug where a client sets fields it should not (isAdmin, role) because the server saves the request body straight into the database.", lesson: 3, group: "API" },
    { term: "GraphQL", full: "GraphQL", desc: "An API style where one endpoint returns exactly the fields the client asks for, described by a typed schema.", lesson: 9, group: "API" },
    { term: "Hasura", full: "Hasura", desc: "A server that generates a GraphQL API over Postgres, with role-based row permissions, compiling nested queries to single SQL statements.", lesson: 9, group: "API" },
    { term: "persisted queries", aliases: ["persisted query"], full: "Persisted queries", desc: "Pre-registered GraphQL queries the client calls by hash, making them cacheable and allowing a server allow-list.", lesson: 9, group: "API" },
    { term: "DataLoader", full: "DataLoader", desc: "A utility that collects lookups made in the same tick and runs them as one batched query. Create one per request.", lesson: 8, group: "API" },
    // ── Errors and operations ──────────────────────────────────────────────
    { term: "operational error", aliases: ["operational errors"], full: "Operational error", desc: "An expected run-time failure in a correct program: bad input, a missing record, a timeout. Handle it and report it.", lesson: 4, group: "Errors and operations" },
    { term: "programmer error", aliases: ["programmer errors"], full: "Programmer error", desc: "A bug, such as reading a property of null. Log it with the stack and restart rather than carry on in an unknown state.", lesson: 4, group: "Errors and operations" },
    { term: "graceful shutdown", full: "Graceful shutdown", desc: "On SIGTERM: stop taking new connections, finish in-flight requests, close the database, then exit.", lesson: 4, group: "Errors and operations" },
    { term: "structured logging", aliases: ["structured logs"], full: "Structured logging", desc: "Logging each event as a JSON object with fields (requestId, userId, durationMs) so tools can search and aggregate it.", lesson: 5, group: "Errors and operations" },
    { term: "correlation ID", aliases: ["request ID", "requestId", "correlation IDs"], full: "Correlation ID", desc: "A unique ID given to each request and attached to every log line and downstream call, so one request can be followed end to end.", lesson: 5, group: "Errors and operations" },
    { term: "RED", full: "Rate, Errors, Duration", desc: "Three metrics for every service: how many requests, how many fail, and how long they take (as percentiles).", lesson: 5, group: "Errors and operations" },
    { term: "OpenTelemetry", full: "OpenTelemetry", desc: "The standard toolkit for producing traces, metrics and logs and sending them to a backend of your choice.", lesson: 5, group: "Errors and operations" },
    // ── Security ───────────────────────────────────────────────────────────
    { term: "Argon2id", full: "Argon2id", desc: "The recommended password hashing algorithm: deliberately slow and memory-hungry, with a built-in salt.", lesson: 6, group: "Security" },
    { term: "IDOR", full: "Insecure Direct Object Reference", desc: "Changing an ID in a URL and seeing someone else's data because the server never checked ownership. Also called BOLA.", lesson: 6, group: "Security" },
    { term: "BOLA", full: "Broken Object Level Authorization", desc: "OWASP's name for IDOR in APIs: the endpoint authenticates the caller but does not check access to that specific object.", lesson: 6, group: "Security" },
    { term: "RBAC", full: "Role-Based Access Control", desc: "Permissions are granted to roles (admin, editor), and users are given roles.", lesson: 6, group: "Security" },
    { term: "ABAC", full: "Attribute-Based Access Control", desc: "Access decisions use attributes of the user, the resource and the context, allowing finer rules than roles.", lesson: 6, group: "Security" },
    { term: "session fixation", full: "Session fixation", desc: "An attacker plants a known session ID before login. Prevented by issuing a fresh ID when the user logs in.", lesson: 6, group: "Security" },
    // ── Database ───────────────────────────────────────────────────────────
    { term: "ACID", full: "Atomicity, Consistency, Isolation, Durability", desc: "The four guarantees of a database transaction: all or nothing, valid state, isolated from others, and surviving a crash.", lesson: 7, group: "Database" },
    { term: "B-tree", full: "B-tree index", desc: "The default database index: values kept sorted in a tree so lookups, ranges and sorts take logarithmic time.", lesson: 7, group: "Database" },
    { term: "EXPLAIN ANALYZE", full: "EXPLAIN ANALYZE", desc: "A PostgreSQL command that runs a query and shows the plan it used, with real timings and row counts.", lesson: 7, group: "Database" },
    { term: "isolation level", aliases: ["isolation levels"], full: "Transaction isolation level", desc: "How much concurrent transactions can see of each other: Read Committed, Repeatable Read or Serializable.", lesson: 7, group: "Database" },
    { term: "write skew", full: "Write skew", desc: "Two transactions read overlapping data and write different rows, together breaking a rule neither broke alone. Needs Serializable to prevent.", lesson: 7, group: "Database" },
    { term: "N+1", aliases: ["N+1 problem"], full: "N+1 query problem", desc: "One query for a list, then one more per row. 100 users means 101 queries. Fixed by eager loading or batching.", lesson: 8, group: "Database" },
    { term: "connection pool", aliases: ["connection pools"], full: "Connection pool", desc: "A fixed set of reusable database connections shared by requests, because opening connections is expensive.", lesson: 8, group: "Database" },
    { term: "PgBouncer", full: "PgBouncer", desc: "A lightweight PostgreSQL connection pooler. Many app instances connect to it; it multiplexes them onto few real connections.", lesson: 8, group: "Database" },
    // ── Node ───────────────────────────────────────────────────────────────
    { term: "event loop", full: "Event loop", desc: "Node's single thread that runs JavaScript callbacks one at a time. Blocking it stalls every request.", lesson: 10, group: "Node" },
    { term: "backpressure", full: "Backpressure", desc: "A slow consumer telling the producer to pause so data does not pile up in memory. Built into Node streams.", lesson: 10, group: "Node" },
    { term: "worker_threads", aliases: ["worker threads"], full: "Worker threads", desc: "Extra threads inside one Node process for CPU-heavy work, so the main event loop stays free.", lesson: 10, group: "Node" },
    { term: "ReDoS", full: "Regular-expression Denial of Service", desc: "A regex with catastrophic backtracking that freezes the process on a small hostile input.", lesson: 10, group: "Node" },
    // ── Testing ────────────────────────────────────────────────────────────
    { term: "contract test", aliases: ["contract tests"], full: "Contract test", desc: "A check that the request and response shapes two systems rely on have not changed, so a rename cannot silently break the other side.", lesson: 11, group: "Testing" },
    { term: "Supertest", full: "Supertest", desc: "A library for calling an Express app through HTTP in tests without opening a real port.", lesson: 11, group: "Testing" },
    { term: "Testcontainers", full: "Testcontainers", desc: "A library that starts a throwaway Docker container (such as Postgres) from test code.", lesson: 11, group: "Testing" },
  ],
  debugging: [{ term: "INP", full: "Interaction to Next Paint", desc: "A Core Web Vital measuring how quickly the page responds to clicks, taps and key presses.", lesson: 1, group: "Metrics" }],
  "design-problems": [{ term: "Base62", full: "Base62", desc: "An encoding using 0-9, a-z and A-Z: 62 URL-safe characters.", lesson: 1, group: "Encoding" }],
  "frontend-depth": [{ term: "Reconciliation", full: "Reconciliation", desc: "How React compares the new tree of elements with the previous one to decide what to change.", lesson: 0, group: "React" }],
};
