import type { GlossaryEntry } from "./glossary";

/** Terms per interview series (key = series slug). Filled in alongside the lessons. */
export const IV_TERMS: Record<string, GlossaryEntry[]> = {
  browser: [
    // ── Network ────────────────────────────────────────────────────────────
    { term: "DNS", full: "Domain Name System", desc: "The internet's phone book: turns a name like react.dev into an IP address. Answers are cached according to a TTL.", lesson: 0, group: "Network" },
    { term: "TCP", full: "Transmission Control Protocol", desc: "The reliable, ordered connection underneath HTTP/1.1 and HTTP/2. Opening one costs a three-way handshake, one round trip.", lesson: 0, group: "Network" },
    { term: "QUIC", full: "QUIC", desc: "The UDP-based transport under HTTP/3. It merges the transport and TLS handshakes and avoids TCP's head-of-line blocking.", lesson: 0, group: "Network" },
    { term: "TLS", full: "Transport Layer Security", desc: "The encryption layer behind HTTPS. The browser checks the server's certificate and both sides agree on session keys.", lesson: 0, group: "Network" },
    { term: "RTT", full: "Round-trip time", desc: "How long a packet takes to reach the server and come back. Every handshake costs at least one RTT, which is why distance matters.", lesson: 0, group: "Network" },
    { term: "TTL", full: "Time to live", desc: "How long a DNS answer may be cached before it must be looked up again.", lesson: 0, group: "Network" },
    { term: "CDN", full: "Content Delivery Network", desc: "Servers around the world that keep copies of your files close to users, cutting distance and load on your origin.", lesson: 5, group: "Network" },
    { term: "HSTS", full: "HTTP Strict Transport Security", desc: "A header telling the browser to use HTTPS only for this site, so it never sends an insecure first request.", lesson: 0, group: "Network" },
    { term: "bfcache", full: "Back/forward cache", desc: "Lets the browser restore an entire page, JavaScript state included, from memory when you press Back or Forward.", lesson: 0, group: "Network" },
    // ── HTTP ───────────────────────────────────────────────────────────────
    { term: "CORS", full: "Cross-Origin Resource Sharing", desc: "Headers with which a server lets other origins read its responses. Enforced by browsers only; it is not a firewall.", lesson: 4, group: "HTTP" },
    { term: "preflight", aliases: ["Preflight"], full: "CORS preflight", desc: "An OPTIONS request the browser sends first to ask whether a cross-origin request with a given method or headers is allowed.", lesson: 4, group: "HTTP" },
    { term: "ETag", full: "Entity tag", desc: "A fingerprint of a response. The browser sends it back in If-None-Match so the server can answer 304 Not Modified instead of resending the body.", lesson: 5, group: "HTTP" },
    { term: "idempotent", aliases: ["Idempotent", "idempotency"], full: "Idempotent", desc: "Doing it once or many times leaves the server in the same state, so it is safe to retry. PUT and DELETE are; POST is not.", lesson: 6, group: "HTTP" },
    { term: "Origin", full: "Origin", desc: "Scheme + host + port. Two URLs are same-origin only if all three match; the same-origin policy is built on it.", lesson: 4, group: "HTTP" },
    { term: "TTFB", full: "Time to First Byte", desc: "Time from sending the request to receiving the first byte of the response: network time plus all server work.", lesson: 0, group: "HTTP" },
    // ── Storage and auth ───────────────────────────────────────────────────
    { term: "HttpOnly", full: "HttpOnly cookie attribute", desc: "Hides the cookie from JavaScript, so an XSS payload cannot read it. It cannot stop the payload from using the session.", lesson: 1, group: "Storage and auth" },
    { term: "SameSite", full: "SameSite cookie attribute", desc: "Strict, Lax or None: whether the cookie is sent on cross-site requests. The main built-in CSRF defence.", lesson: 1, group: "Storage and auth" },
    { term: "IndexedDB", full: "IndexedDB", desc: "An asynchronous, transactional database in the browser for large or structured data, usable from workers.", lesson: 1, group: "Storage and auth" },
    { term: "JWT", full: "JSON Web Token", desc: "A signed token of three base64url parts (header.payload.signature). Readable by anyone who holds it; the signature proves it was not altered.", lesson: 2, group: "Storage and auth" },
    { term: "JWKS", full: "JSON Web Key Set", desc: "A published list of public keys that services use to verify tokens signed with a private key.", lesson: 2, group: "Storage and auth" },
    { term: "refresh token", aliases: ["Refresh token", "refresh tokens"], full: "Refresh token", desc: "A longer-lived credential used only to get new short-lived access tokens, ideally rotated on every use.", lesson: 2, group: "Storage and auth" },
    { term: "BFF", full: "Backend for Frontend", desc: "A server you own between the browser and downstream APIs. It holds the tokens so the browser only ever has a session cookie.", lesson: 3, group: "Storage and auth" },
    // ── Security ───────────────────────────────────────────────────────────
    { term: "XSS", full: "Cross-Site Scripting", desc: "An attacker gets their JavaScript to run on your origin, so it can read storage and act as the user.", lesson: 3, group: "Security" },
    { term: "CSRF", full: "Cross-Site Request Forgery", desc: "Another site makes the victim's browser send a request to yours, and the browser attaches the cookies automatically.", lesson: 3, group: "Security" },
    { term: "CSP", full: "Content Security Policy", desc: "A response header listing which sources of scripts, styles and frames the browser may use. A backstop if escaping fails.", lesson: 7, group: "Security" },
    { term: "SRI", full: "Subresource Integrity", desc: "An integrity hash on a script or stylesheet tag. The browser refuses the file if its content does not match.", lesson: 7, group: "Security" },
    { term: "nonce", aliases: ["Nonce"], full: "Nonce", desc: "A random one-time value generated per response and used to mark which inline scripts a CSP allows.", lesson: 7, group: "Security" },
    { term: "clickjacking", aliases: ["Clickjacking"], full: "Clickjacking", desc: "Framing your site invisibly on another page to trick users into clicking your buttons. Stopped by frame-ancestors.", lesson: 7, group: "Security" },
    // ── Rendering and performance ──────────────────────────────────────────
    { term: "DOM", full: "Document Object Model", desc: "The tree of elements the browser builds from your HTML. JavaScript reads and changes the page through it.", lesson: 0, group: "Rendering and performance" },
    { term: "CSSOM", full: "CSS Object Model", desc: "The browser's tree of styles. Painting waits for it, which is why CSS blocks rendering.", lesson: 0, group: "Rendering and performance" },
    { term: "hydration", aliases: ["Hydration"], full: "Hydration", desc: "React re-running on the client over server-rendered HTML to attach event handlers. Until it finishes, buttons look ready but do nothing.", lesson: 0, group: "Rendering and performance" },
    { term: "reflow", aliases: ["Reflow"], full: "Reflow (layout)", desc: "Recalculating the size and position of elements. Expensive, and triggered by changing width, height, margin and similar.", lesson: 8, group: "Rendering and performance" },
    { term: "layout thrashing", aliases: ["Layout thrashing"], full: "Layout thrashing", desc: "Alternating layout reads and style writes in a loop so the browser recalculates layout every iteration.", lesson: 8, group: "Rendering and performance" },
    { term: "long task", aliases: ["long tasks", "Long task"], full: "Long task", desc: "Any task that holds the main thread for more than 50 ms, delaying input and painting.", lesson: 8, group: "Rendering and performance" },
    { term: "LCP", full: "Largest Contentful Paint", desc: "When the largest visible element (usually the hero image or heading) is painted. Good is 2.5 s or less.", lesson: 9, group: "Rendering and performance" },
    { term: "INP", full: "Interaction to Next Paint", desc: "How long the page takes to visually respond to clicks, taps and keys, across the whole visit. Good is 200 ms or less. Replaced FID in 2024.", lesson: 9, group: "Rendering and performance" },
    { term: "CLS", full: "Cumulative Layout Shift", desc: "A score for how much visible content jumps around unexpectedly. Good is 0.1 or less.", lesson: 9, group: "Rendering and performance" },
    { term: "FID", full: "First Input Delay", desc: "The old responsiveness metric: only the delay before the first interaction was handled. Replaced by INP.", lesson: 9, group: "Rendering and performance" },
    { term: "FCP", full: "First Contentful Paint", desc: "When the first text or image appears on screen.", lesson: 0, group: "Rendering and performance" },
    { term: "TBT", full: "Total Blocking Time", desc: "A lab metric: the total time the main thread was blocked by long tasks. Used as a proxy for INP in Lighthouse.", lesson: 9, group: "Rendering and performance" },
    { term: "CrUX", full: "Chrome UX Report", desc: "Google's dataset of real-user performance measurements, used by PageSpeed Insights and Search Console.", lesson: 9, group: "Rendering and performance" },
    { term: "RUM", full: "Real User Monitoring", desc: "Measuring performance from real visitors' browsers rather than in a lab test.", lesson: 9, group: "Rendering and performance" },
  ],
  backend: [
    // ── Design ─────────────────────────────────────────────────────────────
    { term: "SOLID", full: "SOLID principles", desc: "Five design principles: single responsibility, open/closed, Liskov substitution, interface segregation and dependency inversion.", lesson: 0, group: "Design" },
    { term: "DRY", full: "Don't Repeat Yourself", desc: "Keep one source of truth for each piece of knowledge. It is about shared rules, not identical-looking text.", lesson: 0, group: "Design" },
    { term: "DTO", full: "Data Transfer Object", desc: "A plain object that defines the shape of data crossing a boundary, such as a request body or response, separate from the database model.", lesson: 3, group: "Design" },
    { term: "dependency injection", aliases: ["Dependency injection"], full: "Dependency injection", desc: "Passing a function the things it needs (repository, clock, gateway) instead of letting it import or create them.", lesson: 0, group: "Design" },
    { term: "controller", aliases: ["controllers"], full: "Controller", desc: "The layer that translates HTTP to a service call and back: reads the request, calls one service function, shapes the response.", lesson: 1, group: "Design" },
    { term: "repository", aliases: ["repositories"], full: "Repository", desc: "The layer that owns data access. Only it knows about the ORM or SQL.", lesson: 1, group: "Design" },
    // ── API ────────────────────────────────────────────────────────────────
    { term: "REST", full: "Representational State Transfer", desc: "An API style built on resources (nouns) identified by URLs and manipulated with HTTP methods and status codes.", lesson: 2, group: "API" },
    { term: "OpenAPI", full: "OpenAPI Specification", desc: "A machine-readable description of a REST API, used for docs, generated types and breaking-change checks.", lesson: 2, group: "API" },
    { term: "idempotency key", aliases: ["Idempotency-Key", "idempotency keys"], full: "Idempotency key", desc: "A unique value the client sends with a POST so the server can detect a retry and return the first result instead of repeating the work.", lesson: 2, group: "API" },
    { term: "problem details", aliases: ["Problem Details"], full: "Problem Details for HTTP APIs", desc: "A standard JSON error format (type, title, status, detail) served as application/problem+json.", lesson: 2, group: "API" },
    { term: "mass assignment", aliases: ["over-posting"], full: "Mass assignment", desc: "A bug where a client sets fields it should not (isAdmin, role) because the server saves the request body straight into the database.", lesson: 3, group: "API" },
    { term: "GraphQL", full: "GraphQL", desc: "An API style where one endpoint returns exactly the fields the client asks for, described by a typed schema.", lesson: 9, group: "API" },
    { term: "Hasura", full: "Hasura", desc: "A server that generates a GraphQL API over Postgres, with role-based row permissions, compiling nested queries to single SQL statements.", lesson: 9, group: "API" },
    { term: "persisted queries", aliases: ["persisted query"], full: "Persisted queries", desc: "Pre-registered GraphQL queries the client calls by hash, making them cacheable and allowing a server allow-list.", lesson: 9, group: "API" },
    { term: "DataLoader", full: "DataLoader", desc: "A utility that collects lookups made in the same tick and runs them as one batched query. Create one per request.", lesson: 8, group: "API" },
    // ── Errors and operations ──────────────────────────────────────────────
    { term: "operational error", aliases: ["operational errors"], full: "Operational error", desc: "An expected run-time failure in a correct program: bad input, a missing record, a timeout. Handle it and report it.", lesson: 4, group: "Errors and operations" },
    { term: "programmer error", aliases: ["programmer errors"], full: "Programmer error", desc: "A bug, such as reading a property of null. Log it with the stack and restart rather than carry on in an unknown state.", lesson: 4, group: "Errors and operations" },
    { term: "graceful shutdown", full: "Graceful shutdown", desc: "On SIGTERM: stop taking new connections, finish in-flight requests, close the database, then exit.", lesson: 4, group: "Errors and operations" },
    { term: "structured logging", aliases: ["structured logs"], full: "Structured logging", desc: "Logging each event as a JSON object with fields (requestId, userId, durationMs) so tools can search and aggregate it.", lesson: 5, group: "Errors and operations" },
    { term: "correlation ID", aliases: ["request ID", "requestId", "correlation IDs"], full: "Correlation ID", desc: "A unique ID given to each request and attached to every log line and downstream call, so one request can be followed end to end.", lesson: 5, group: "Errors and operations" },
    { term: "RED", full: "Rate, Errors, Duration", desc: "Three metrics for every service: how many requests, how many fail, and how long they take (as percentiles).", lesson: 5, group: "Errors and operations" },
    { term: "OpenTelemetry", full: "OpenTelemetry", desc: "The standard toolkit for producing traces, metrics and logs and sending them to a backend of your choice.", lesson: 5, group: "Errors and operations" },
    // ── Security ───────────────────────────────────────────────────────────
    { term: "Argon2id", full: "Argon2id", desc: "The recommended password hashing algorithm: deliberately slow and memory-hungry, with a built-in salt.", lesson: 6, group: "Security" },
    { term: "IDOR", full: "Insecure Direct Object Reference", desc: "Changing an ID in a URL and seeing someone else's data because the server never checked ownership. Also called BOLA.", lesson: 6, group: "Security" },
    { term: "BOLA", full: "Broken Object Level Authorization", desc: "OWASP's name for IDOR in APIs: the endpoint authenticates the caller but does not check access to that specific object.", lesson: 6, group: "Security" },
    { term: "RBAC", full: "Role-Based Access Control", desc: "Permissions are granted to roles (admin, editor), and users are given roles.", lesson: 6, group: "Security" },
    { term: "ABAC", full: "Attribute-Based Access Control", desc: "Access decisions use attributes of the user, the resource and the context, allowing finer rules than roles.", lesson: 6, group: "Security" },
    { term: "session fixation", full: "Session fixation", desc: "An attacker plants a known session ID before login. Prevented by issuing a fresh ID when the user logs in.", lesson: 6, group: "Security" },
    // ── Database ───────────────────────────────────────────────────────────
    { term: "ACID", full: "Atomicity, Consistency, Isolation, Durability", desc: "The four guarantees of a database transaction: all or nothing, valid state, isolated from others, and surviving a crash.", lesson: 7, group: "Database" },
    { term: "B-tree", full: "B-tree index", desc: "The default database index: values kept sorted in a tree so lookups, ranges and sorts take logarithmic time.", lesson: 7, group: "Database" },
    { term: "EXPLAIN ANALYZE", full: "EXPLAIN ANALYZE", desc: "A PostgreSQL command that runs a query and shows the plan it used, with real timings and row counts.", lesson: 7, group: "Database" },
    { term: "isolation level", aliases: ["isolation levels"], full: "Transaction isolation level", desc: "How much concurrent transactions can see of each other: Read Committed, Repeatable Read or Serializable.", lesson: 7, group: "Database" },
    { term: "write skew", full: "Write skew", desc: "Two transactions read overlapping data and write different rows, together breaking a rule neither broke alone. Needs Serializable to prevent.", lesson: 7, group: "Database" },
    { term: "N+1", aliases: ["N+1 problem"], full: "N+1 query problem", desc: "One query for a list, then one more per row. 100 users means 101 queries. Fixed by eager loading or batching.", lesson: 8, group: "Database" },
    { term: "connection pool", aliases: ["connection pools"], full: "Connection pool", desc: "A fixed set of reusable database connections shared by requests, because opening connections is expensive.", lesson: 8, group: "Database" },
    { term: "PgBouncer", full: "PgBouncer", desc: "A lightweight PostgreSQL connection pooler. Many app instances connect to it; it multiplexes them onto few real connections.", lesson: 8, group: "Database" },
    // ── Node ───────────────────────────────────────────────────────────────
    { term: "event loop", full: "Event loop", desc: "Node's single thread that runs JavaScript callbacks one at a time. Blocking it stalls every request.", lesson: 10, group: "Node" },
    { term: "backpressure", full: "Backpressure", desc: "A slow consumer telling the producer to pause so data does not pile up in memory. Built into Node streams.", lesson: 10, group: "Node" },
    { term: "worker_threads", aliases: ["worker threads"], full: "Worker threads", desc: "Extra threads inside one Node process for CPU-heavy work, so the main event loop stays free.", lesson: 10, group: "Node" },
    { term: "ReDoS", full: "Regular-expression Denial of Service", desc: "A regex with catastrophic backtracking that freezes the process on a small hostile input.", lesson: 10, group: "Node" },
    // ── Testing ────────────────────────────────────────────────────────────
    { term: "contract test", aliases: ["contract tests"], full: "Contract test", desc: "A check that the request and response shapes two systems rely on have not changed, so a rename cannot silently break the other side.", lesson: 11, group: "Testing" },
    { term: "Supertest", full: "Supertest", desc: "A library for calling an Express app through HTTP in tests without opening a real port.", lesson: 11, group: "Testing" },
    { term: "Testcontainers", full: "Testcontainers", desc: "A library that starts a throwaway Docker container (such as Postgres) from test code.", lesson: 11, group: "Testing" },
  ],
  debugging: [
    // ── Method ─────────────────────────────────────────────────────────────
    { term: "p95", aliases: ["p99", "p50", "percentile", "percentiles"], full: "Percentile latency", desc: "p95 is the value below which 95% of requests fall. Percentiles show what the slowest users feel; averages hide them.", lesson: 0, group: "Method" },
    { term: "baseline", aliases: ["Baseline"], full: "Baseline", desc: "The measured starting number (same device, same conditions) you compare against to prove a change helped.", lesson: 0, group: "Method" },
    { term: "field data", aliases: ["Field data"], full: "Field data", desc: "Measurements from real users' browsers (RUM, CrUX). Tells you whether and for whom there is a problem.", lesson: 0, group: "Method" },
    { term: "lab data", aliases: ["Lab data"], full: "Lab data", desc: "Measurements from a controlled test (Lighthouse, DevTools with throttling). Good for reproducing and verifying fixes.", lesson: 0, group: "Method" },
    { term: "Server-Timing", full: "Server-Timing header", desc: "A response header where the server reports how long each of its steps took. DevTools shows it in the request's Timing tab.", lesson: 2, group: "Method" },
    { term: "APM", full: "Application Performance Monitoring", desc: "Tools that trace requests through your services and show where time goes (Datadog, New Relic, X-Ray).", lesson: 2, group: "Method" },
    // ── Frontend performance ───────────────────────────────────────────────
    { term: "main thread", aliases: ["Main thread"], full: "Main thread", desc: "The single browser thread that runs your JavaScript and builds every frame. Long work on it blocks input and painting.", lesson: 1, group: "Frontend performance" },
    { term: "useDeferredValue", full: "useDeferredValue", desc: "A React hook returning a copy of a value that lags behind during heavy renders, keeping typing responsive.", lesson: 1, group: "Frontend performance" },
    { term: "startTransition", full: "startTransition", desc: "Marks a React state update as non-urgent so it can be rendered in the background and interrupted by urgent input.", lesson: 1, group: "Frontend performance" },
    { term: "Profiler", aliases: ["React Profiler"], full: "React Profiler", desc: "A React DevTools panel that records renders and shows which components rendered, how long they took and why.", lesson: 3, group: "Frontend performance" },
    { term: "memo", full: "React.memo", desc: "Wraps a component so React skips re-rendering it when its props are shallowly equal. Needs stable props to help.", lesson: 3, group: "Frontend performance" },
    { term: "colocate", aliases: ["colocation"], full: "State colocation", desc: "Keeping state in the smallest component that needs it, so changes re-render only that part of the tree.", lesson: 3, group: "Frontend performance" },
    { term: "virtualization", aliases: ["virtualisation", "Virtualization", "windowing"], full: "List virtualization", desc: "Rendering only the rows visible in the viewport (plus a few extra) and recycling them as you scroll. Keeps the DOM small.", lesson: 7, group: "Frontend performance" },
    { term: "Web Worker", aliases: ["Web Workers"], full: "Web Worker", desc: "A background thread for heavy JavaScript so the main thread stays free. It talks to the page by messages.", lesson: 7, group: "Frontend performance" },
    { term: "code splitting", aliases: ["Code splitting"], full: "Code splitting", desc: "Breaking the JavaScript bundle into chunks loaded on demand, so each page or feature loads only what it needs.", lesson: 6, group: "Frontend performance" },
    { term: "tree-shaking", aliases: ["tree shaking"], full: "Tree-shaking", desc: "A build step that removes exports nobody imports. Works best with ES module imports of single functions.", lesson: 6, group: "Frontend performance" },
    { term: "preload", full: "preload", desc: "A hint to fetch a resource needed for the current page right now, at high priority (the LCP image, a key font).", lesson: 6, group: "Frontend performance" },
    { term: "prefetch", full: "prefetch", desc: "A hint to fetch something likely needed on a future navigation, at low priority during idle time.", lesson: 6, group: "Frontend performance" },
    { term: "bundle", aliases: ["bundles"], full: "JavaScript bundle", desc: "The built JavaScript file(s) the browser downloads. Its parsed size drives CPU cost; its compressed size drives network cost.", lesson: 6, group: "Frontend performance" },
    { term: "Strict Mode", full: "React Strict Mode", desc: "A development-only mode that renders twice and remounts effects once to expose impure code and missing cleanup.", lesson: 5, group: "Frontend performance" },
    { term: "content-visibility", full: "content-visibility", desc: "A CSS property that lets the browser skip layout and paint of off-screen sections until they near the viewport.", lesson: 7, group: "Frontend performance" },
    // ── Reliability and data ───────────────────────────────────────────────
    { term: "memory leak", aliases: ["memory leaks", "Memory leak"], full: "Memory leak", desc: "Memory that is no longer needed but still referenced, so the garbage collector cannot free it.", lesson: 4, group: "Reliability and data" },
    { term: "heap snapshot", aliases: ["heap snapshots", "Heap snapshot"], full: "Heap snapshot", desc: "A DevTools capture of every object in memory. Compare two snapshots to find objects that keep growing.", lesson: 4, group: "Reliability and data" },
    { term: "retainer", aliases: ["retainers", "Retainers"], full: "Retainer", desc: "The chain of references from a GC root to an object. It tells you what is keeping a leaked object alive.", lesson: 4, group: "Reliability and data" },
    { term: "detached DOM node", aliases: ["detached DOM nodes", "Detached"], full: "Detached DOM node", desc: "An element removed from the page but still referenced by JavaScript, so its whole subtree stays in memory.", lesson: 4, group: "Reliability and data" },
    { term: "AbortController", full: "AbortController", desc: "Cancels an in-flight fetch (or removes listeners) through a signal. Aborted fetches reject with an AbortError.", lesson: 5, group: "Reliability and data" },
    { term: "race condition", aliases: ["race conditions"], full: "Race condition", desc: "A bug where the result depends on which of several async operations finishes first, such as an old response overwriting a new one.", lesson: 5, group: "Reliability and data" },
    { term: "debounce", aliases: ["debouncing", "Debounce"], full: "Debounce", desc: "Waiting until input pauses before acting, so typing triggers one request instead of one per keystroke.", lesson: 5, group: "Reliability and data" },
    { term: "cache-aside", aliases: ["Cache-aside"], full: "Cache-aside", desc: "Check the cache first; on a miss, load from the source and store it. Writes invalidate or update the cache entry.", lesson: 2, group: "Reliability and data" },
    { term: "cache stampede", aliases: ["stampede"], full: "Cache stampede", desc: "When a hot key expires and thousands of requests miss at once, all hitting the database. Prevented by coalescing and jittered TTLs.", lesson: 2, group: "Reliability and data" },
    { term: "cold start", aliases: ["cold starts"], full: "Cold start", desc: "The extra delay when a serverless function or scaled-to-zero container handles its first request after being idle.", lesson: 2, group: "Reliability and data" },
    { term: "keepAliveTimeout", full: "Keep-alive timeout", desc: "How long Node keeps an idle connection open. If it is shorter than the load balancer's idle timeout, you get random 502s.", lesson: 9, group: "Reliability and data" },
    { term: "CLS", full: "Cumulative Layout Shift", desc: "A score for how much visible content jumps unexpectedly while loading. Fixed by reserving space.", lesson: 8, group: "Frontend performance" },
    { term: "LoAF", full: "Long Animation Frames", desc: "A Chrome API and DevTools insight that attributes long frames to the scripts and callbacks responsible.", lesson: 8, group: "Frontend performance" },
  ],
  "design-problems": [
    // ── Method ─────────────────────────────────────────────────────────────
    { term: "QPS", aliases: ["RPS"], full: "Queries (requests) per second", desc: "The request rate. A million requests a day is about 12 per second; multiply by 2 to 10 for peak.", lesson: 0, group: "Method" },
    { term: "read-heavy", aliases: ["read:write"], full: "Read-heavy", desc: "A system with far more reads than writes, so caches and replicas matter most. A URL shortener is about 100 to 1.", lesson: 0, group: "Method" },
    { term: "trade-off", aliases: ["trade-offs"], full: "Trade-off", desc: "A choice that gains one thing by giving up another. Good answers name both sides and when they would choose differently.", lesson: 0, group: "Method" },
    // ── Encoding and IDs ───────────────────────────────────────────────────
    { term: "Base62", full: "Base62", desc: "An encoding using 0-9, a-z and A-Z: 62 URL-safe characters. Seven of them give about 3.5 trillion codes.", lesson: 1, group: "Encoding and IDs" },
    { term: "collision", aliases: ["collisions"], full: "Collision", desc: "Two different inputs producing the same code. Handled by a unique constraint and a retry.", lesson: 1, group: "Encoding and IDs" },
    { term: "KGS", full: "Key Generation Service", desc: "A service that pre-generates unique short codes and hands them out in batches, so nothing needs checking at request time.", lesson: 1, group: "Encoding and IDs" },
    { term: "301", full: "301 Moved Permanently", desc: "A cacheable permanent redirect. Browsers may skip your server on repeat visits, losing analytics.", lesson: 1, group: "Encoding and IDs" },
    { term: "302", full: "302 Found", desc: "A temporary redirect that browsers do not cache by default, so every click reaches your server.", lesson: 1, group: "Encoding and IDs" },
    { term: "SSRF", full: "Server-Side Request Forgery", desc: "Tricking your server into fetching an internal address (like a cloud metadata endpoint) by giving it a crafted URL.", lesson: 1, group: "Encoding and IDs" },
    // ── Rate limiting ──────────────────────────────────────────────────────
    { term: "token bucket", aliases: ["Token bucket"], full: "Token bucket", desc: "A bucket refilled at a steady rate; each request takes a token. Allows bursts up to capacity while enforcing an average rate.", lesson: 2, group: "Rate limiting" },
    { term: "leaky bucket", aliases: ["Leaky bucket"], full: "Leaky bucket", desc: "Requests queue and drain at a constant rate, smoothing bursts into steady output.", lesson: 2, group: "Rate limiting" },
    { term: "sliding window", aliases: ["Sliding window"], full: "Sliding window", desc: "Counting requests over the last N seconds at any moment, avoiding the double-burst at fixed-window boundaries.", lesson: 2, group: "Rate limiting" },
    { term: "429", full: "429 Too Many Requests", desc: "The status code for rate limiting, sent with a Retry-After header telling the client when to try again.", lesson: 2, group: "Rate limiting" },
    { term: "Retry-After", full: "Retry-After header", desc: "A header giving the number of seconds (or a date) after which the client may retry.", lesson: 2, group: "Rate limiting" },
    { term: "fail open", aliases: ["fail-open"], full: "Fail open", desc: "If the limiter is down, allow requests. Keeps the API up, but unprotected.", lesson: 2, group: "Rate limiting" },
    { term: "fail closed", aliases: ["fail-closed"], full: "Fail closed", desc: "If the limiter is down, reject requests. Right for login and OTP, where unlimited attempts enable brute force.", lesson: 2, group: "Rate limiting" },
    { term: "Lua", full: "Lua script (Redis)", desc: "A small script Redis runs atomically, so a read-modify-write like a token-bucket update cannot race.", lesson: 2, group: "Rate limiting" },
    // ── Data access ────────────────────────────────────────────────────────
    { term: "keyset pagination", aliases: ["cursor pagination", "Keyset pagination"], full: "Keyset (cursor) pagination", desc: "Paging by 'rows after the last one I saw' using the sort key, so it stays fast and stable at any depth.", lesson: 3, group: "Data access" },
    { term: "OFFSET", aliases: ["offset pagination"], full: "OFFSET pagination", desc: "Skipping N rows with LIMIT/OFFSET. Simple, but the database reads and discards N rows, and results shift when data changes.", lesson: 3, group: "Data access" },
    { term: "tiebreaker", full: "Tiebreaker column", desc: "A unique column (usually the ID) added to the sort so rows with equal values have a fixed order.", lesson: 3, group: "Data access" },
    { term: "opaque cursor", aliases: ["cursor"], full: "Opaque cursor", desc: "A token the client passes back without understanding it, so the server can change its contents freely.", lesson: 3, group: "Data access" },
    { term: "Relay", full: "Relay connections", desc: "GraphQL's standard cursor pagination: edges with cursors plus pageInfo (hasNextPage, endCursor).", lesson: 3, group: "Data access" },
    // ── Uploads and delivery ───────────────────────────────────────────────
    { term: "presigned URL", aliases: ["presigned URLs", "Presigned URL"], full: "Presigned URL", desc: "A time-limited URL signed with your credentials that lets the holder upload or download one object directly to storage.", lesson: 4, group: "Uploads and delivery" },
    { term: "multipart upload", aliases: ["Multipart upload"], full: "Multipart upload", desc: "Splitting a large file into parts uploaded in parallel and retried individually, then assembled by the storage service.", lesson: 4, group: "Uploads and delivery" },
    { term: "magic bytes", full: "Magic bytes", desc: "The first bytes of a file that identify its real type. Check them instead of trusting the extension or Content-Type.", lesson: 4, group: "Uploads and delivery" },
    { term: "DLQ", aliases: ["dead-letter queue", "dead letter queue"], full: "Dead-letter queue", desc: "A side queue for messages that keep failing, so they stop blocking the main queue and can be inspected and replayed.", lesson: 5, group: "Uploads and delivery" },
    { term: "SSE", aliases: ["Server-Sent Events"], full: "Server-Sent Events", desc: "A one-way stream from server to browser over HTTP with automatic reconnect and resume through Last-Event-ID.", lesson: 5, group: "Uploads and delivery" },
    { term: "WebSocket", aliases: ["WebSockets"], full: "WebSocket", desc: "A two-way connection between browser and server, opened by an HTTP upgrade. Use when the client also sends frequent messages.", lesson: 5, group: "Uploads and delivery" },
    { term: "fan-out", aliases: ["Fan-out"], full: "Fan-out", desc: "Turning one event into many deliveries, such as one broadcast into a million notifications.", lesson: 5, group: "Uploads and delivery" },
    { term: "at-least-once", aliases: ["At-least-once"], full: "At-least-once delivery", desc: "A message may arrive more than once but is never lost, so consumers must be idempotent.", lesson: 5, group: "Uploads and delivery" },
    // ── Classic components ─────────────────────────────────────────────────
    { term: "trie", aliases: ["Trie"], full: "Trie (prefix tree)", desc: "A tree where each path spells a prefix. Storing top suggestions on each node answers autocomplete in O(prefix length).", lesson: 6, group: "Classic components" },
    { term: "combobox", aliases: ["Combobox"], full: "ARIA combobox", desc: "The accessibility pattern for an input with a popup list of options, wired with aria-expanded and aria-activedescendant.", lesson: 6, group: "Classic components" },
    { term: "IME", full: "Input Method Editor", desc: "Software for typing languages like Chinese or Japanese in several composition steps. Don't search mid-composition.", lesson: 6, group: "Classic components" },
    { term: "LRU", full: "Least Recently Used", desc: "A cache that evicts the entry unused for the longest time. A hash map plus a doubly linked list gives O(1).", lesson: 7, group: "Classic components" },
    { term: "jitter", aliases: ["Jitter"], full: "Jitter", desc: "Randomness added to retry delays so many clients do not retry at the same moment.", lesson: 7, group: "Classic components" },
    { term: "exponential backoff", aliases: ["Exponential backoff", "backoff"], full: "Exponential backoff", desc: "Doubling the wait between retries (1 s, 2 s, 4 s…), up to a cap, so a struggling service can recover.", lesson: 7, group: "Classic components" },
    { term: "circuit breaker", aliases: ["Circuit breaker"], full: "Circuit breaker", desc: "After repeated failures, stop calling a dependency for a while and fail fast, then probe to see if it has recovered.", lesson: 7, group: "Classic components" },
    { term: "feature flag", aliases: ["feature flags", "Feature flag"], full: "Feature flag", desc: "A switch that turns a feature on or off, or rolls it out to a percentage of users, without redeploying.", lesson: 7, group: "Classic components" },
    { term: "kill switch", full: "Kill switch", desc: "A flag that instantly disables a feature during an incident.", lesson: 7, group: "Classic components" },
  ],
  "frontend-depth": [
    // ── React model ────────────────────────────────────────────────────────
    { term: "reconciliation", aliases: ["Reconciliation"], full: "Reconciliation", desc: "How React compares the new tree of elements with the previous one, using element type and key, to decide what to update, keep or remount.", lesson: 0, group: "React model" },
    { term: "render phase", aliases: ["Render phase"], full: "Render phase", desc: "React calls your components to compute the next UI. It must be pure: no side effects, because React may repeat or discard it.", lesson: 0, group: "React model" },
    { term: "commit phase", aliases: ["Commit phase"], full: "Commit phase", desc: "React applies the minimal DOM changes, then runs layout effects (before paint) and passive effects (after paint). It cannot be interrupted.", lesson: 0, group: "React model" },
    { term: "Fiber", full: "React Fiber", desc: "React's internal tree of work units. It is what makes rendering interruptible and lets state attach to a position in the tree.", lesson: 0, group: "React model" },
    { term: "batching", aliases: ["Batching", "automatic batching"], full: "Batching", desc: "React grouping several state updates from one event or tick into a single re-render.", lesson: 0, group: "React model" },
    { term: "stale closure", aliases: ["stale closures"], full: "Stale closure", desc: "A function that keeps seeing old values because it captured them from an earlier render, usually due to missing effect dependencies.", lesson: 1, group: "React model" },
    { term: "useEffect", full: "useEffect", desc: "Runs after render to synchronise a component with something outside React: a subscription, timer or network request. Needs cleanup.", lesson: 1, group: "React model" },
    { term: "useLayoutEffect", full: "useLayoutEffect", desc: "Like useEffect but runs after DOM changes and before the browser paints. For measuring layout without flicker.", lesson: 1, group: "React model" },
    { term: "useRef", full: "useRef", desc: "A mutable box that survives renders without causing one. Used for DOM nodes, timer IDs and 'latest value' holders.", lesson: 1, group: "React model" },
    { term: "useReducer", full: "useReducer", desc: "State managed by a pure (state, action) => state function. Good for complex transitions.", lesson: 1, group: "React model" },
    // ── Modern React ───────────────────────────────────────────────────────
    { term: "Suspense", full: "Suspense", desc: "A React boundary that shows a fallback while something inside it (code or data) is still loading.", lesson: 2, group: "Modern React" },
    { term: "useTransition", full: "useTransition", desc: "Marks a state update as non-urgent so React can render it in the background and let urgent input go first.", lesson: 2, group: "Modern React" },
    { term: "streaming", aliases: ["Streaming", "streaming SSR"], full: "Streaming SSR", desc: "The server sends the HTML shell immediately and streams slower Suspense sections as they finish.", lesson: 2, group: "Modern React" },
    { term: "RSC", aliases: ["Server Component", "Server Components"], full: "React Server Components", desc: "Components that run only on the server and send no JavaScript to the browser. They can read data directly.", lesson: 2, group: "Modern React" },
    { term: "use client", full: "\"use client\" directive", desc: "Marks a module as the start of the client bundle. It and everything it imports run in the browser.", lesson: 2, group: "Modern React" },
    { term: "Server Action", aliases: ["Server Actions"], full: "Server Action", desc: "A function marked \"use server\" that runs on the server but can be called from the client. It is a public endpoint, so it needs auth and validation.", lesson: 2, group: "Modern React" },
    { term: "hydration mismatch", aliases: ["hydration error"], full: "Hydration mismatch", desc: "The first client render differs from the server HTML, usually because of dates, random values or browser-only APIs in render.", lesson: 2, group: "Modern React" },
    // ── State ──────────────────────────────────────────────────────────────
    { term: "server state", aliases: ["Server state"], full: "Server state", desc: "Data that lives on the server and is only cached in the UI. Needs revalidation, dedupe and invalidation. Use TanStack Query or SWR.", lesson: 3, group: "State" },
    { term: "TanStack Query", aliases: ["React Query"], full: "TanStack Query (React Query)", desc: "A library that caches, dedupes, revalidates and updates server data by query key.", lesson: 3, group: "State" },
    { term: "Zustand", full: "Zustand", desc: "A tiny store library. Components subscribe to slices with selectors and re-render only when their slice changes.", lesson: 3, group: "State" },
    { term: "selector", aliases: ["selectors"], full: "Selector", desc: "A function that picks the slice of a store a component cares about, so unrelated changes do not re-render it.", lesson: 3, group: "State" },
    // ── TypeScript ─────────────────────────────────────────────────────────
    { term: "generic", aliases: ["generics", "Generics"], full: "Generic", desc: "A type parameter that lets one function or type work for many types while keeping their relationships.", lesson: 4, group: "TypeScript" },
    { term: "discriminated union", aliases: ["discriminated unions"], full: "Discriminated union", desc: "A union where every variant has a literal tag property. Checking the tag narrows the type and enables exhaustive checks.", lesson: 4, group: "TypeScript" },
    { term: "narrowing", aliases: ["Narrowing"], full: "Type narrowing", desc: "TypeScript refining a value's type inside a branch after a check like typeof, in or a tag comparison.", lesson: 4, group: "TypeScript" },
    { term: "unknown", full: "unknown", desc: "The safe top type: a value you know nothing about, which must be narrowed or validated before use. Prefer it to any.", lesson: 4, group: "TypeScript" },
    { term: "satisfies", full: "satisfies operator", desc: "Checks a value against a type without widening it, so you keep the precise inferred type.", lesson: 4, group: "TypeScript" },
    { term: "Zod", full: "Zod", desc: "A TypeScript-first schema library: one schema validates data at runtime and gives you the static type through z.infer.", lesson: 4, group: "TypeScript" },
    // ── Testing and a11y ───────────────────────────────────────────────────
    { term: "Testing Library", aliases: ["React Testing Library", "RTL"], full: "Testing Library", desc: "Tests components the way users meet them: query by role, label and text, interact with user-event.", lesson: 5, group: "Testing and accessibility" },
    { term: "MSW", full: "Mock Service Worker", desc: "Intercepts network requests in tests (and dev) so real components run against fake responses.", lesson: 5, group: "Testing and accessibility" },
    { term: "Playwright", full: "Playwright", desc: "A browser automation tool for end-to-end tests, with auto-waiting locators and web-first assertions.", lesson: 5, group: "Testing and accessibility" },
    { term: "storageState", full: "Playwright storageState", desc: "Saved cookies and local storage from a login, reused so tests start authenticated without repeating the login UI.", lesson: 5, group: "Testing and accessibility" },
    { term: "snapshot test", aliases: ["snapshot tests", "snapshot"], full: "Snapshot test", desc: "A test that stores output and fails when it changes. Good for small stable values, noisy for big DOM trees.", lesson: 5, group: "Testing and accessibility" },
    { term: "ARIA", full: "Accessible Rich Internet Applications", desc: "Attributes that add accessibility semantics HTML cannot express. They change what is announced, not what an element does.", lesson: 6, group: "Testing and accessibility" },
    { term: "WCAG", full: "Web Content Accessibility Guidelines", desc: "The standard for accessible web content. Level AA asks for 4.5:1 text contrast, keyboard operability and more.", lesson: 6, group: "Testing and accessibility" },
    { term: "focus trap", aliases: ["Focus trap"], full: "Focus trap", desc: "Keeping Tab and Shift+Tab inside a modal while it is open. The native dialog element does this for you.", lesson: 6, group: "Testing and accessibility" },
    { term: "live region", aliases: ["live regions"], full: "ARIA live region", desc: "An element whose changes are announced by screen readers: role=\"status\" (polite) or role=\"alert\" (urgent).", lesson: 6, group: "Testing and accessibility" },
    { term: "accessible name", full: "Accessible name", desc: "The text a screen reader announces for a control, from its label, content or aria-label.", lesson: 6, group: "Testing and accessibility" },
  ],
};
