import type { GlossaryEntry } from "./glossary";

/** Terms per interview series (key = series slug). Filled in alongside the lessons. */
export const IV_TERMS: Record<string, GlossaryEntry[]> = {
  browser: [
    // ── Network ────────────────────────────────────────────────────────────
    { term: "DNS", full: "Domain Name System", desc: "The internet's phone book. It turns a name like react.dev into an IP address (the number of a server). Answers are saved for a set time (the TTL).", lesson: 0, group: "Network" },
    { term: "TCP", full: "Transmission Control Protocol", desc: "A reliable way to send data in order. HTTP/1.1 and HTTP/2 use it. Opening a connection takes a short hello exchange that costs one round trip.", lesson: 0, group: "Network" },
    { term: "QUIC", full: "QUIC", desc: "A newer way to send data, used by HTTP/3. It joins the connection hello and the encryption hello into one. One lost packet does not stop the others.", lesson: 0, group: "Network" },
    { term: "TLS", full: "Transport Layer Security", desc: "The encryption behind HTTPS. The browser checks the server's certificate (its ID card). Then both sides agree on a secret key.", lesson: 0, group: "Network" },
    { term: "RTT", full: "Round-trip time", desc: "How long a message takes to reach the server and come back. Every hello costs at least one RTT, so a far-away server feels slower.", lesson: 0, group: "Network" },
    { term: "TTL", full: "Time to live", desc: "How long a saved DNS answer may be used before the browser must ask again.", lesson: 0, group: "Network" },
    { term: "CDN", full: "Content Delivery Network", desc: "Servers around the world that keep copies of your files. Users get files from a nearby server, so it is faster and your own server has less work.", lesson: 5, group: "Network" },
    { term: "HSTS", full: "HTTP Strict Transport Security", desc: "A header that tells the browser: always use HTTPS for this site. The browser then never sends the first request in plain, unsafe form.", lesson: 0, group: "Network" },
    { term: "bfcache", full: "Back/forward cache", desc: "The browser keeps a whole page in memory, with its JavaScript state. When you press Back or Forward, the page appears again at once.", lesson: 0, group: "Network" },
    // ── HTTP ───────────────────────────────────────────────────────────────
    { term: "CORS", full: "Cross-Origin Resource Sharing", desc: "A set of headers where a server says which other sites may read its answers. Only browsers enforce it. It does not protect the server like a firewall.", lesson: 4, group: "HTTP" },
    { term: "preflight", aliases: ["Preflight"], full: "CORS preflight", desc: "A small OPTIONS request the browser sends first. It asks: is this cross-site request with this method or these headers allowed?", lesson: 4, group: "HTTP" },
    { term: "ETag", full: "Entity tag", desc: "A fingerprint of a response. The browser sends it back in If-None-Match. If nothing changed, the server replies 304 Not Modified and skips the body.", lesson: 5, group: "HTTP" },
    { term: "idempotent", aliases: ["Idempotent", "idempotency"], full: "Idempotent", desc: "Doing it once or many times gives the same result, so a retry is safe. PUT and DELETE are idempotent. POST is not.", lesson: 6, group: "HTTP" },
    { term: "Origin", full: "Origin", desc: "Scheme + host + port together (for example https://site.com:443). Two URLs are the same origin only if all three match.", lesson: 4, group: "HTTP" },
    { term: "TTFB", full: "Time to First Byte", desc: "Time from sending the request to receiving the first byte of the answer. It includes network time and the server's work.", lesson: 0, group: "HTTP" },
    // ── Storage and auth ───────────────────────────────────────────────────
    { term: "HttpOnly", full: "HttpOnly cookie attribute", desc: "A cookie setting that hides the cookie from JavaScript. An XSS attack cannot read it, but it can still use the logged-in session.", lesson: 1, group: "Storage and auth" },
    { term: "SameSite", full: "SameSite cookie attribute", desc: "A cookie setting (Strict, Lax or None) that says if the cookie is sent on requests from other sites. It is the main built-in defence against CSRF.", lesson: 1, group: "Storage and auth" },
    { term: "IndexedDB", full: "IndexedDB", desc: "A database inside the browser for large or structured data. It does not block the page, and workers can use it too.", lesson: 1, group: "Storage and auth" },
    { term: "JWT", full: "JSON Web Token", desc: "A signed token with three parts: header.payload.signature. Anyone who has it can read it. The signature shows that nobody changed it.", lesson: 2, group: "Storage and auth" },
    { term: "JWKS", full: "JSON Web Key Set", desc: "A public list of keys. Services use it to check tokens that were signed with a secret key.", lesson: 2, group: "Storage and auth" },
    { term: "refresh token", aliases: ["Refresh token", "refresh tokens"], full: "Refresh token", desc: "A long-lived token used only to get a new short-lived access token. Best practice is to replace it each time it is used.", lesson: 2, group: "Storage and auth" },
    { term: "BFF", full: "Backend for Frontend", desc: "A server you own between the browser and other APIs. It keeps the tokens, so the browser only holds a session cookie.", lesson: 3, group: "Storage and auth" },
    // ── Security ───────────────────────────────────────────────────────────
    { term: "XSS", full: "Cross-Site Scripting", desc: "An attacker makes their JavaScript run on your site. That code can read stored data and act as the user.", lesson: 3, group: "Security" },
    { term: "CSRF", full: "Cross-Site Request Forgery", desc: "Another site makes the user's browser send a request to your site. The browser adds the user's cookies by itself.", lesson: 3, group: "Security" },
    { term: "CSP", full: "Content Security Policy", desc: "A response header that lists which sources of scripts, styles and frames are allowed. It is a safety net if escaping fails.", lesson: 7, group: "Security" },
    { term: "SRI", full: "Subresource Integrity", desc: "A hash added to a script or style tag. The browser refuses the file if its content does not match the hash.", lesson: 7, group: "Security" },
    { term: "nonce", aliases: ["Nonce"], full: "Nonce", desc: "A random one-time value made for each response. It marks which inline scripts the CSP allows.", lesson: 7, group: "Security" },
    { term: "clickjacking", aliases: ["Clickjacking"], full: "Clickjacking", desc: "An attacker shows your site invisibly inside their page, so users click your buttons by mistake. The frame-ancestors setting stops it.", lesson: 7, group: "Security" },
    // ── Rendering and performance ──────────────────────────────────────────
    { term: "DOM", full: "Document Object Model", desc: "The tree of elements the browser builds from your HTML. JavaScript reads and changes the page through it.", lesson: 0, group: "Rendering and performance" },
    { term: "CSSOM", full: "CSS Object Model", desc: "The browser's tree of styles. The browser waits for it before it paints, so CSS can block the first paint.", lesson: 0, group: "Rendering and performance" },
    { term: "hydration", aliases: ["Hydration"], full: "Hydration", desc: "React runs again in the browser on HTML that the server made. It adds the click handlers. Before it finishes, buttons look ready but do nothing.", lesson: 0, group: "Rendering and performance" },
    { term: "reflow", aliases: ["Reflow"], full: "Reflow (layout)", desc: "The browser works out the size and place of elements again. It is costly. Changing width, height or margin causes it.", lesson: 8, group: "Rendering and performance" },
    { term: "layout thrashing", aliases: ["Layout thrashing"], full: "Layout thrashing", desc: "Reading layout and writing styles again and again in a loop. The browser must redo the layout on every turn.", lesson: 8, group: "Rendering and performance" },
    { term: "long task", aliases: ["long tasks", "Long task"], full: "Long task", desc: "A task that blocks the main thread for more than 50 ms. Clicks and painting must wait.", lesson: 8, group: "Rendering and performance" },
    { term: "LCP", full: "Largest Contentful Paint", desc: "The time when the largest visible item (often the main image or heading) is painted. Good is 2.5 seconds or less.", lesson: 9, group: "Rendering and performance" },
    { term: "INP", full: "Interaction to Next Paint", desc: "How long the page takes to show a reaction to clicks, taps and key presses, over the whole visit. Good is 200 ms or less. It replaced FID in 2024.", lesson: 9, group: "Rendering and performance" },
    { term: "CLS", full: "Cumulative Layout Shift", desc: "A score for how much the page content jumps around by surprise. Good is 0.1 or less.", lesson: 9, group: "Rendering and performance" },
    { term: "FID", full: "First Input Delay", desc: "The old speed metric. It measured only the wait before the first click was handled. INP replaced it.", lesson: 9, group: "Rendering and performance" },
    { term: "FCP", full: "First Contentful Paint", desc: "The time when the first text or image shows on screen.", lesson: 0, group: "Rendering and performance" },
    { term: "TBT", full: "Total Blocking Time", desc: "A lab number: the total time long tasks blocked the main thread. Lighthouse uses it as a stand-in for INP.", lesson: 9, group: "Rendering and performance" },
    { term: "CrUX", full: "Chrome UX Report", desc: "Google's data from real users' browsers. PageSpeed Insights and Search Console use it.", lesson: 9, group: "Rendering and performance" },
    { term: "RUM", full: "Real User Monitoring", desc: "Measuring speed in the browsers of real visitors, not only in a lab test.", lesson: 9, group: "Rendering and performance" },
  ],
  backend: [
    // ── Design ─────────────────────────────────────────────────────────────
    { term: "SOLID", full: "SOLID principles", desc: "Five design rules: single responsibility, open/closed, Liskov substitution, interface segregation and dependency inversion.", lesson: 0, group: "Design" },
    { term: "DRY", full: "Don't Repeat Yourself", desc: "Keep one place for each piece of knowledge. It is about shared rules, not about code that only looks the same.", lesson: 0, group: "Design" },
    { term: "DTO", full: "Data Transfer Object", desc: "A plain object that sets the shape of data that crosses a border, like a request body or response. It is separate from the database model.", lesson: 3, group: "Design" },
    { term: "dependency injection", aliases: ["Dependency injection"], full: "Dependency injection", desc: "Give a function the things it needs (a repository, a clock) from outside. Do not let it import or create them itself.", lesson: 0, group: "Design" },
    { term: "controller", aliases: ["controllers"], full: "Controller", desc: "The layer between HTTP and your logic. It reads the request, calls one service function and builds the response.", lesson: 1, group: "Design" },
    { term: "repository", aliases: ["repositories"], full: "Repository", desc: "The layer that owns data access. Only it knows about the ORM or the SQL.", lesson: 1, group: "Design" },
    // ── API ────────────────────────────────────────────────────────────────
    { term: "REST", full: "Representational State Transfer", desc: "An API style built on resources (nouns) with URLs. You use HTTP methods and status codes to work with them.", lesson: 2, group: "API" },
    { term: "OpenAPI", full: "OpenAPI Specification", desc: "A file that describes a REST API so machines can read it. It is used for docs, generated types and checks for breaking changes.", lesson: 2, group: "API" },
    { term: "idempotency key", aliases: ["Idempotency-Key", "idempotency keys"], full: "Idempotency key", desc: "A unique value the client sends with a POST. If the request is sent again, the server sees the key and returns the first result. It does not repeat the work.", lesson: 2, group: "API" },
    { term: "problem details", aliases: ["Problem Details"], full: "Problem Details for HTTP APIs", desc: "A standard JSON error format with type, title, status and detail. It is sent as application/problem+json.", lesson: 2, group: "API" },
    { term: "mass assignment", aliases: ["over-posting"], full: "Mass assignment", desc: "A bug where a client sets fields it should not (like isAdmin) because the server saves the whole request body into the database.", lesson: 3, group: "API" },
    { term: "GraphQL", full: "GraphQL", desc: "An API style with one endpoint. The client asks for exactly the fields it wants. A typed schema describes the data.", lesson: 9, group: "API" },
    { term: "Hasura", full: "Hasura", desc: "A server that makes a GraphQL API from a Postgres database. It has role-based row permissions and turns nested queries into one SQL statement.", lesson: 9, group: "API" },
    { term: "persisted queries", aliases: ["persisted query"], full: "Persisted queries", desc: "GraphQL queries saved on the server in advance. The client sends only a hash. This makes them cacheable and lets the server allow only known queries.", lesson: 9, group: "API" },
    { term: "DataLoader", full: "DataLoader", desc: "A tool that collects lookups made in the same moment and runs them as one query. Make one per request.", lesson: 8, group: "API" },
    // ── Errors and operations ──────────────────────────────────────────────
    { term: "operational error", aliases: ["operational errors"], full: "Operational error", desc: "An expected failure in a correct program, like bad input, a missing record or a timeout. Handle it and report it.", lesson: 4, group: "Errors and operations" },
    { term: "programmer error", aliases: ["programmer errors"], full: "Programmer error", desc: "A bug in the code, like reading a property of null. Log it with the stack trace and restart. Do not carry on in an unknown state.", lesson: 4, group: "Errors and operations" },
    { term: "graceful shutdown", full: "Graceful shutdown", desc: "When the process gets SIGTERM: stop taking new connections, finish the running requests, close the database, then exit.", lesson: 4, group: "Errors and operations" },
    { term: "structured logging", aliases: ["structured logs"], full: "Structured logging", desc: "Writing each log event as a JSON object with fields (requestId, userId, durationMs). Tools can then search and count the logs.", lesson: 5, group: "Errors and operations" },
    { term: "correlation ID", aliases: ["request ID", "requestId", "correlation IDs"], full: "Correlation ID", desc: "A unique ID for each request. It goes on every log line and every call to other services, so you can follow one request from start to end.", lesson: 5, group: "Errors and operations" },
    { term: "RED", full: "Rate, Errors, Duration", desc: "Three numbers to watch for every service: how many requests, how many fail, and how long they take (as percentiles).", lesson: 5, group: "Errors and operations" },
    { term: "OpenTelemetry", full: "OpenTelemetry", desc: "A standard toolkit to create traces, metrics and logs and send them to the tool you choose.", lesson: 5, group: "Errors and operations" },
    // ── Security ───────────────────────────────────────────────────────────
    { term: "Argon2id", full: "Argon2id", desc: "The recommended way to hash passwords. It is slow and uses much memory on purpose, and it adds a salt (random extra data) by itself.", lesson: 6, group: "Security" },
    { term: "IDOR", full: "Insecure Direct Object Reference", desc: "Someone changes an ID in a URL and sees another person's data, because the server never checked who owns it. Also called BOLA.", lesson: 6, group: "Security" },
    { term: "BOLA", full: "Broken Object Level Authorization", desc: "OWASP's name for IDOR in APIs. The endpoint checks who the caller is, but not whether the caller may use that specific object.", lesson: 6, group: "Security" },
    { term: "RBAC", full: "Role-Based Access Control", desc: "Permissions go to roles (like admin or editor). Users are given roles.", lesson: 6, group: "Security" },
    { term: "ABAC", full: "Attribute-Based Access Control", desc: "Access rules use facts about the user, the resource and the situation. This allows finer rules than roles.", lesson: 6, group: "Security" },
    { term: "session fixation", full: "Session fixation", desc: "An attacker sets a known session ID before the user logs in. Stop it by creating a new ID at login.", lesson: 6, group: "Security" },
    // ── Database ───────────────────────────────────────────────────────────
    { term: "ACID", full: "Atomicity, Consistency, Isolation, Durability", desc: "Four promises of a database transaction: all or nothing, always valid, separate from other transactions, and safe after a crash.", lesson: 7, group: "Database" },
    { term: "B-tree", full: "B-tree index", desc: "The default database index. Values are kept sorted in a tree, so finding a value, a range or a sort order is fast.", lesson: 7, group: "Database" },
    { term: "EXPLAIN ANALYZE", full: "EXPLAIN ANALYZE", desc: "A PostgreSQL command. It runs a query and shows the plan it used, with real times and row counts.", lesson: 7, group: "Database" },
    { term: "isolation level", aliases: ["isolation levels"], full: "Transaction isolation level", desc: "How much one running transaction can see of another. The levels are Read Committed, Repeatable Read and Serializable.", lesson: 7, group: "Database" },
    { term: "write skew", full: "Write skew", desc: "Two transactions read the same data and then write different rows. Together they break a rule that neither broke alone. Only Serializable prevents it.", lesson: 7, group: "Database" },
    { term: "N+1", aliases: ["N+1 problem"], full: "N+1 query problem", desc: "One query for a list, then one more query for each row. With 100 users you make 101 queries. Fix it with eager loading or batching.", lesson: 8, group: "Database" },
    { term: "connection pool", aliases: ["connection pools"], full: "Connection pool", desc: "A fixed set of database connections that requests share and reuse. Opening a new connection costs a lot.", lesson: 8, group: "Database" },
    { term: "PgBouncer", full: "PgBouncer", desc: "A light tool that pools PostgreSQL connections. Many app copies connect to it, and it shares a few real connections between them.", lesson: 8, group: "Database" },
    // ── Node ───────────────────────────────────────────────────────────────
    { term: "event loop", full: "Event loop", desc: "Node's single thread that runs JavaScript callbacks one at a time. If you block it, every request waits.", lesson: 10, group: "Node" },
    { term: "backpressure", full: "Backpressure", desc: "A slow reader tells the sender to pause, so data does not pile up in memory. Node streams do this for you.", lesson: 10, group: "Node" },
    { term: "worker_threads", aliases: ["worker threads"], full: "Worker threads", desc: "Extra threads inside one Node process for heavy CPU work. The main event loop stays free.", lesson: 10, group: "Node" },
    { term: "ReDoS", full: "Regular-expression Denial of Service", desc: "A regular expression that can take forever on some input (catastrophic backtracking). A small bad input can freeze the process.", lesson: 10, group: "Node" },
    // ── Testing ────────────────────────────────────────────────────────────
    { term: "contract test", aliases: ["contract tests"], full: "Contract test", desc: "A test that checks the shape of requests and responses between two systems. A rename then cannot break the other side without a warning.", lesson: 11, group: "Testing" },
    { term: "Supertest", full: "Supertest", desc: "A library that calls your Express app through HTTP in tests, without opening a real port.", lesson: 11, group: "Testing" },
    { term: "Testcontainers", full: "Testcontainers", desc: "A library that starts a temporary Docker container (like Postgres) from your test code.", lesson: 11, group: "Testing" },
  ],
  debugging: [
    // ── Method ─────────────────────────────────────────────────────────────
    { term: "p95", aliases: ["p99", "p50", "percentile", "percentiles"], full: "Percentile latency", desc: "p95 is the time that 95% of requests beat. Percentiles show what your slowest users feel. An average hides them.", lesson: 0, group: "Method" },
    { term: "baseline", aliases: ["Baseline"], full: "Baseline", desc: "The starting number you measured (same device, same conditions). You compare with it to prove a change helped.", lesson: 0, group: "Method" },
    { term: "field data", aliases: ["Field data"], full: "Field data", desc: "Measurements from real users' browsers (RUM, CrUX). They tell you if there is a problem and who has it.", lesson: 0, group: "Method" },
    { term: "lab data", aliases: ["Lab data"], full: "Lab data", desc: "Measurements from a controlled test (Lighthouse, DevTools with throttling). Good for repeating a problem and checking a fix.", lesson: 0, group: "Method" },
    { term: "Server-Timing", full: "Server-Timing header", desc: "A response header where the server reports how long each of its steps took. DevTools shows it in the Timing tab.", lesson: 2, group: "Method" },
    { term: "APM", full: "Application Performance Monitoring", desc: "Tools that follow a request through your services and show where the time goes (Datadog, New Relic, X-Ray).", lesson: 2, group: "Method" },
    // ── Frontend performance ───────────────────────────────────────────────
    { term: "main thread", aliases: ["Main thread"], full: "Main thread", desc: "The one browser thread that runs your JavaScript and builds every frame. Long work on it blocks clicks and painting.", lesson: 1, group: "Frontend performance" },
    { term: "useDeferredValue", full: "useDeferredValue", desc: "A React hook that gives a copy of a value that updates a little later. It keeps typing smooth while a heavy render runs.", lesson: 1, group: "Frontend performance" },
    { term: "startTransition", full: "startTransition", desc: "Marks a React state update as not urgent. React can render it in the background, and urgent input can interrupt it.", lesson: 1, group: "Frontend performance" },
    { term: "Profiler", aliases: ["React Profiler"], full: "React Profiler", desc: "A React DevTools panel. It records renders and shows which components rendered, how long it took and why.", lesson: 3, group: "Frontend performance" },
    { term: "memo", full: "React.memo", desc: "Wraps a component so React skips its re-render if the props did not change (a shallow check). The props must stay the same between renders to help.", lesson: 3, group: "Frontend performance" },
    { term: "colocate", aliases: ["colocation"], full: "State colocation", desc: "Keep state in the smallest component that needs it. A change then re-renders only that part of the tree.", lesson: 3, group: "Frontend performance" },
    { term: "virtualization", aliases: ["virtualisation", "Virtualization", "windowing"], full: "List virtualization", desc: "Draw only the rows you can see (plus a few more) and reuse them as you scroll. The DOM stays small.", lesson: 7, group: "Frontend performance" },
    { term: "Web Worker", aliases: ["Web Workers"], full: "Web Worker", desc: "A background thread for heavy JavaScript, so the main thread stays free. It talks to the page with messages.", lesson: 7, group: "Frontend performance" },
    { term: "code splitting", aliases: ["Code splitting"], full: "Code splitting", desc: "Cut the JavaScript bundle into pieces that load when needed. Each page loads only what it uses.", lesson: 6, group: "Frontend performance" },
    { term: "tree-shaking", aliases: ["tree shaking"], full: "Tree-shaking", desc: "A build step that removes code nobody imports. It works best when you import single functions from ES modules.", lesson: 6, group: "Frontend performance" },
    { term: "preload", full: "preload", desc: "A hint to download a file the current page needs right now, with high priority (the LCP image, an important font).", lesson: 6, group: "Frontend performance" },
    { term: "prefetch", full: "prefetch", desc: "A hint to download something the user will probably need on a later page, with low priority, when the browser is idle.", lesson: 6, group: "Frontend performance" },
    { term: "bundle", aliases: ["bundles"], full: "JavaScript bundle", desc: "The built JavaScript file(s) the browser downloads. Parsed size costs CPU time. Compressed size costs network time.", lesson: 6, group: "Frontend performance" },
    { term: "Strict Mode", full: "React Strict Mode", desc: "A mode for development only. It renders twice and remounts effects once, to show impure code and missing cleanup.", lesson: 5, group: "Frontend performance" },
    { term: "content-visibility", full: "content-visibility", desc: "A CSS property that lets the browser skip layout and painting of off-screen parts until they get close to the screen.", lesson: 7, group: "Frontend performance" },
    // ── Reliability and data ───────────────────────────────────────────────
    { term: "memory leak", aliases: ["memory leaks", "Memory leak"], full: "Memory leak", desc: "Memory that is no longer needed but is still referenced. The garbage collector (the memory cleaner) cannot free it.", lesson: 4, group: "Reliability and data" },
    { term: "heap snapshot", aliases: ["heap snapshots", "Heap snapshot"], full: "Heap snapshot", desc: "A DevTools copy of every object in memory. Compare two snapshots to find objects that keep growing.", lesson: 4, group: "Reliability and data" },
    { term: "retainer", aliases: ["retainers", "Retainers"], full: "Retainer", desc: "The chain of references from a GC root to an object. It shows what keeps a leaked object alive.", lesson: 4, group: "Reliability and data" },
    { term: "detached DOM node", aliases: ["detached DOM nodes", "Detached"], full: "Detached DOM node", desc: "An element that was removed from the page but is still referenced by JavaScript. Its whole subtree stays in memory.", lesson: 4, group: "Reliability and data" },
    { term: "AbortController", full: "AbortController", desc: "Cancels a running fetch (or removes listeners) with a signal. A cancelled fetch fails with an AbortError.", lesson: 5, group: "Reliability and data" },
    { term: "race condition", aliases: ["race conditions"], full: "Race condition", desc: "A bug where the result depends on which async job finishes first. For example, an old response replaces a newer one.", lesson: 5, group: "Reliability and data" },
    { term: "debounce", aliases: ["debouncing", "Debounce"], full: "Debounce", desc: "Wait until the user stops typing, then act. Typing then sends one request, not one per key.", lesson: 5, group: "Reliability and data" },
    { term: "cache-aside", aliases: ["Cache-aside"], full: "Cache-aside", desc: "Check the cache first. If it is empty (a miss), load from the source and save it. A write removes or updates the saved entry.", lesson: 2, group: "Reliability and data" },
    { term: "cache stampede", aliases: ["stampede"], full: "Cache stampede", desc: "A popular cache entry expires, and thousands of requests miss at once and hit the database together. Stop it by merging requests and adding random time to TTLs.", lesson: 2, group: "Reliability and data" },
    { term: "cold start", aliases: ["cold starts"], full: "Cold start", desc: "The extra wait when a serverless function or an idle container handles its first request.", lesson: 2, group: "Reliability and data" },
    { term: "keepAliveTimeout", full: "Keep-alive timeout", desc: "How long Node keeps an idle connection open. If it is shorter than the load balancer's idle time, you get random 502 errors.", lesson: 9, group: "Reliability and data" },
    { term: "CLS", full: "Cumulative Layout Shift", desc: "A score for how much visible content jumps by surprise while the page loads. Fix it by reserving space.", lesson: 8, group: "Frontend performance" },
    { term: "LoAF", full: "Long Animation Frames", desc: "A Chrome API and DevTools tool. It shows which scripts and callbacks made a frame slow.", lesson: 8, group: "Frontend performance" },
    // ── Incidents and judgement ────────────────────────────────────────────
    { term: "postmortem", aliases: ["postmortems", "Postmortem"], full: "Blameless postmortem", desc: "A written review after an incident: the impact, the timeline, the root causes and action items with owners. Blameless means asking how the system allowed it, not who did it.", lesson: 10, group: "Incidents and judgement" },
    { term: "incident commander", full: "Incident commander", desc: "The person who leads during an incident and makes the decisions. Others investigate and give updates.", lesson: 10, group: "Incidents and judgement" },
    { term: "runbook", aliases: ["runbooks"], full: "Runbook", desc: "Step-by-step instructions for a known alert or failure. The alert itself links to it.", lesson: 10, group: "Incidents and judgement" },
    { term: "canary", aliases: ["canary release", "Canary"], full: "Canary release", desc: "Send a change to a small part of the traffic first and watch the numbers before going wider. Roll back by itself if they look bad.", lesson: 10, group: "Incidents and judgement" },
    { term: "cascading failure", full: "Cascading failure", desc: "One slow part uses up all threads or connections, so other parts fail too, until the whole system is down.", lesson: 10, group: "Incidents and judgement" },
    { term: "bulkhead", aliases: ["bulkheads"], full: "Bulkhead", desc: "A separate pool of resources for each dependency. If one dependency fails, it cannot use up everything.", lesson: 10, group: "Incidents and judgement" },
    { term: "SEV1", aliases: ["SEV2", "SEV3"], full: "Severity level", desc: "A label for how serious an incident is. SEV1 is the worst (everyone affected or data at risk). It decides how fast and how widely you react.", lesson: 10, group: "Incidents and judgement" },
    { term: "expand and contract", aliases: ["Expand and contract", "parallel change"], full: "Expand and contract", desc: "Change a database schema safely in steps that old and new code can both survive: add, write to both, backfill, switch reads, then remove the old.", lesson: 14, group: "Incidents and judgement" },
    { term: "strangler fig", aliases: ["Strangler fig", "strangler"], full: "Strangler fig pattern", desc: "Replace an old system step by step. Send parts of the traffic to the new code behind a front layer, and retire old parts when nobody uses them.", lesson: 14, group: "Incidents and judgement" },
    { term: "SBOM", full: "Software Bill of Materials", desc: "A list of every part and version inside your software. It tells you fast if a new vulnerability affects you.", lesson: 13, group: "Incidents and judgement" },
    { term: "SSRF", full: "Server-Side Request Forgery", desc: "Tricking your server into fetching an internal address (like a cloud metadata endpoint) by sending it a crafted URL.", lesson: 13, group: "Incidents and judgement" },
    { term: "micro-frontend", aliases: ["micro-frontends"], full: "Micro-frontend", desc: "Split a UI into pieces that different teams build and deploy on their own. It is worth it only when team coordination is the problem.", lesson: 12, group: "Incidents and judgement" },
  ],
  "design-problems": [
    // ── Method ─────────────────────────────────────────────────────────────
    { term: "QPS", aliases: ["RPS"], full: "Queries (requests) per second", desc: "The request rate. A million requests a day is about 12 per second. Multiply by 2 to 10 for the busy peak.", lesson: 0, group: "Method" },
    { term: "read-heavy", aliases: ["read:write"], full: "Read-heavy", desc: "A system with many more reads than writes, so caches and replicas matter most. A URL shortener is about 100 reads to 1 write.", lesson: 0, group: "Method" },
    { term: "trade-off", aliases: ["trade-offs"], full: "Trade-off", desc: "A choice that gains one thing and loses another. A good answer names both sides and says when you would choose the other way.", lesson: 0, group: "Method" },
    // ── Encoding and IDs ───────────────────────────────────────────────────
    { term: "Base62", full: "Base62", desc: "A way to write numbers with 0-9, a-z and A-Z: 62 characters that are safe in URLs. Seven characters give about 3.5 trillion codes.", lesson: 1, group: "Encoding and IDs" },
    { term: "collision", aliases: ["collisions"], full: "Collision", desc: "Two different inputs get the same code. Handle it with a unique rule in the database and a retry.", lesson: 1, group: "Encoding and IDs" },
    { term: "KGS", full: "Key Generation Service", desc: "A service that makes unique short codes in advance and hands them out in batches. Nothing needs checking at request time.", lesson: 1, group: "Encoding and IDs" },
    { term: "301", full: "301 Moved Permanently", desc: "A permanent redirect that can be cached. Browsers may skip your server on later visits, so you lose analytics.", lesson: 1, group: "Encoding and IDs" },
    { term: "302", full: "302 Found", desc: "A temporary redirect. Browsers do not cache it by default, so every click reaches your server.", lesson: 1, group: "Encoding and IDs" },
    { term: "SSRF", full: "Server-Side Request Forgery", desc: "Tricking your server into fetching an internal address (like a cloud metadata endpoint) by sending it a crafted URL.", lesson: 1, group: "Encoding and IDs" },
    // ── Rate limiting ──────────────────────────────────────────────────────
    { term: "token bucket", aliases: ["Token bucket"], full: "Token bucket", desc: "A bucket that fills at a steady speed. Each request takes one token. Short bursts are allowed up to the bucket size, but the average rate stays fixed.", lesson: 2, group: "Rate limiting" },
    { term: "leaky bucket", aliases: ["Leaky bucket"], full: "Leaky bucket", desc: "Requests wait in a queue and leave at a constant speed. Bursts become a steady flow.", lesson: 2, group: "Rate limiting" },
    { term: "sliding window", aliases: ["Sliding window"], full: "Sliding window", desc: "Count the requests in the last N seconds, at any moment. This avoids the double burst at the edge of fixed windows.", lesson: 2, group: "Rate limiting" },
    { term: "429", full: "429 Too Many Requests", desc: "The status code for rate limiting. It comes with a Retry-After header that says when to try again.", lesson: 2, group: "Rate limiting" },
    { term: "Retry-After", full: "Retry-After header", desc: "A header with the number of seconds (or a date) after which the client may try again.", lesson: 2, group: "Rate limiting" },
    { term: "fail open", aliases: ["fail-open"], full: "Fail open", desc: "If the limiter is down, let requests through. The API stays up, but it is not protected.", lesson: 2, group: "Rate limiting" },
    { term: "fail closed", aliases: ["fail-closed"], full: "Fail closed", desc: "If the limiter is down, reject requests. This is right for login and OTP, where unlimited tries allow brute force.", lesson: 2, group: "Rate limiting" },
    { term: "Lua", full: "Lua script (Redis)", desc: "A small script that Redis runs in one step, so nothing can interrupt it. A read-then-write like a token bucket update cannot race.", lesson: 2, group: "Rate limiting" },
    // ── Data access ────────────────────────────────────────────────────────
    { term: "keyset pagination", aliases: ["cursor pagination", "Keyset pagination"], full: "Keyset (cursor) pagination", desc: "Page by saying 'give me the rows after the last one I saw', using the sort key. It stays fast and stable at any depth.", lesson: 3, group: "Data access" },
    { term: "OFFSET", aliases: ["offset pagination"], full: "OFFSET pagination", desc: "Skip N rows with LIMIT/OFFSET. It is simple, but the database reads and throws away N rows, and results shift when data changes.", lesson: 3, group: "Data access" },
    { term: "tiebreaker", full: "Tiebreaker column", desc: "A unique column (usually the ID) added to the sort, so rows with equal values always keep the same order.", lesson: 3, group: "Data access" },
    { term: "opaque cursor", aliases: ["cursor"], full: "Opaque cursor", desc: "A token the client sends back without understanding it. The server can change what is inside whenever it wants.", lesson: 3, group: "Data access" },
    { term: "Relay", full: "Relay connections", desc: "GraphQL's standard cursor paging: edges with cursors, plus pageInfo (hasNextPage, endCursor).", lesson: 3, group: "Data access" },
    // ── Uploads and delivery ───────────────────────────────────────────────
    { term: "presigned URL", aliases: ["presigned URLs", "Presigned URL"], full: "Presigned URL", desc: "A web address with a time limit, signed with your credentials. Whoever holds it can upload or download one file directly to storage.", lesson: 4, group: "Uploads and delivery" },
    { term: "multipart upload", aliases: ["Multipart upload"], full: "Multipart upload", desc: "Split a large file into parts. The parts upload in parallel and can be retried one by one. The storage service joins them.", lesson: 4, group: "Uploads and delivery" },
    { term: "magic bytes", full: "Magic bytes", desc: "The first bytes of a file show its real type. Check them. Do not trust the file extension or the Content-Type.", lesson: 4, group: "Uploads and delivery" },
    { term: "DLQ", aliases: ["dead-letter queue", "dead letter queue"], full: "Dead-letter queue", desc: "A side queue for messages that keep failing. They stop blocking the main queue, and you can look at them and replay them.", lesson: 5, group: "Uploads and delivery" },
    { term: "SSE", aliases: ["Server-Sent Events"], full: "Server-Sent Events", desc: "A one-way stream from the server to the browser over HTTP. It reconnects by itself and can resume with Last-Event-ID.", lesson: 5, group: "Uploads and delivery" },
    { term: "WebSocket", aliases: ["WebSockets"], full: "WebSocket", desc: "A two-way connection between browser and server, opened with an HTTP upgrade. Use it when the client also sends messages often.", lesson: 5, group: "Uploads and delivery" },
    { term: "fan-out", aliases: ["Fan-out"], full: "Fan-out", desc: "Turning one event into many deliveries, like one broadcast into a million notifications.", lesson: 5, group: "Uploads and delivery" },
    { term: "at-least-once", aliases: ["At-least-once"], full: "At-least-once delivery", desc: "A message may arrive more than once, but it is never lost. So consumers must be idempotent.", lesson: 5, group: "Uploads and delivery" },
    // ── Classic components ─────────────────────────────────────────────────
    { term: "trie", aliases: ["Trie"], full: "Trie (prefix tree)", desc: "A tree where each path spells a prefix. If each node stores the top suggestions, autocomplete takes O(prefix length).", lesson: 6, group: "Classic components" },
    { term: "combobox", aliases: ["Combobox"], full: "ARIA combobox", desc: "The accessibility pattern for an input with a popup list. It uses aria-expanded and aria-activedescendant.", lesson: 6, group: "Classic components" },
    { term: "IME", full: "Input Method Editor", desc: "Software for typing languages like Chinese or Japanese in several steps. Do not search while the user is still composing.", lesson: 6, group: "Classic components" },
    { term: "LRU", full: "Least Recently Used", desc: "A cache that removes the entry that was not used for the longest time. A hash map plus a doubly linked list makes it O(1).", lesson: 7, group: "Classic components" },
    { term: "jitter", aliases: ["Jitter"], full: "Jitter", desc: "A bit of random time added to retry delays, so many clients do not retry at the same moment.", lesson: 7, group: "Classic components" },
    { term: "exponential backoff", aliases: ["Exponential backoff", "backoff"], full: "Exponential backoff", desc: "Double the wait between retries (1 s, 2 s, 4 s…) up to a limit. A struggling service gets time to recover.", lesson: 7, group: "Classic components" },
    { term: "circuit breaker", aliases: ["Circuit breaker"], full: "Circuit breaker", desc: "After many failures, stop calling a dependency for a while and fail fast. Then test now and then to see if it works again.", lesson: 7, group: "Classic components" },
    { term: "feature flag", aliases: ["feature flags", "Feature flag"], full: "Feature flag", desc: "A switch that turns a feature on or off, or gives it to a share of users, without a new deploy.", lesson: 7, group: "Classic components" },
    { term: "kill switch", full: "Kill switch", desc: "A flag that switches a feature off at once during an incident.", lesson: 7, group: "Classic components" },
  ],
  "frontend-depth": [
    // ── React model ────────────────────────────────────────────────────────
    { term: "reconciliation", aliases: ["Reconciliation"], full: "Reconciliation", desc: "How React compares the new tree of elements with the old one, using type and key. It decides what to update, keep or remount.", lesson: 0, group: "React model" },
    { term: "render phase", aliases: ["Render phase"], full: "Render phase", desc: "React calls your components to work out the next UI. It must be pure (no side effects), because React may repeat it or throw it away.", lesson: 0, group: "React model" },
    { term: "commit phase", aliases: ["Commit phase"], full: "Commit phase", desc: "React applies the smallest DOM changes. Then it runs layout effects (before paint) and passive effects (after paint). It cannot be interrupted.", lesson: 0, group: "React model" },
    { term: "Fiber", full: "React Fiber", desc: "React's inside tree of work units. It lets React pause rendering, and it lets state belong to a place in the tree.", lesson: 0, group: "React model" },
    { term: "batching", aliases: ["Batching", "automatic batching"], full: "Batching", desc: "React groups several state updates from one event into a single re-render.", lesson: 0, group: "React model" },
    { term: "stale closure", aliases: ["stale closures"], full: "Stale closure", desc: "A function that keeps seeing old values, because it captured them in an earlier render. Missing effect dependencies often cause it.", lesson: 1, group: "React model" },
    { term: "useEffect", full: "useEffect", desc: "Runs after render to connect a component to something outside React, like a subscription, timer or network request. It needs cleanup.", lesson: 1, group: "React model" },
    { term: "useLayoutEffect", full: "useLayoutEffect", desc: "Like useEffect, but it runs after DOM changes and before the browser paints. Use it to measure layout without flicker.", lesson: 1, group: "React model" },
    { term: "useRef", full: "useRef", desc: "A box you can change that survives renders and does not cause a render. Use it for DOM nodes, timer IDs and 'latest value' holders.", lesson: 1, group: "React model" },
    { term: "useReducer", full: "useReducer", desc: "State changed by a pure function (state, action) => state. Good for complex changes.", lesson: 1, group: "React model" },
    // ── Modern React ───────────────────────────────────────────────────────
    { term: "Suspense", full: "Suspense", desc: "A React wrapper that shows a fallback while something inside it (code or data) is still loading.", lesson: 2, group: "Modern React" },
    { term: "useTransition", full: "useTransition", desc: "Marks a state update as not urgent. React renders it in the background and lets urgent input go first.", lesson: 2, group: "Modern React" },
    { term: "streaming", aliases: ["Streaming", "streaming SSR"], full: "Streaming SSR", desc: "The server sends the HTML shell at once. Slower Suspense parts arrive later, when they are ready.", lesson: 2, group: "Modern React" },
    { term: "RSC", aliases: ["Server Component", "Server Components"], full: "React Server Components", desc: "Components that run only on the server and send no JavaScript to the browser. They can read data directly.", lesson: 2, group: "Modern React" },
    { term: "use client", full: "\"use client\" directive", desc: "Marks a file as the start of the client bundle. It and everything it imports run in the browser.", lesson: 2, group: "Modern React" },
    { term: "Server Action", aliases: ["Server Actions"], full: "Server Action", desc: "A function marked \"use server\" that runs on the server but can be called from the client. It is a public endpoint, so it needs auth and validation.", lesson: 2, group: "Modern React" },
    { term: "hydration mismatch", aliases: ["hydration error"], full: "Hydration mismatch", desc: "The first render in the browser is different from the server HTML. Dates, random values or browser-only APIs in render often cause it.", lesson: 2, group: "Modern React" },
    // ── State ──────────────────────────────────────────────────────────────
    { term: "server state", aliases: ["Server state"], full: "Server state", desc: "Data that lives on the server and is only copied into the UI. It needs refresh, dedupe and invalidation. Use TanStack Query or SWR.", lesson: 3, group: "State" },
    { term: "TanStack Query", aliases: ["React Query"], full: "TanStack Query (React Query)", desc: "A library that saves server data by query key. It also dedupes, refreshes and updates it.", lesson: 3, group: "State" },
    { term: "Zustand", full: "Zustand", desc: "A tiny store library. Components pick a slice with a selector and re-render only when that slice changes.", lesson: 3, group: "State" },
    { term: "selector", aliases: ["selectors"], full: "Selector", desc: "A function that picks the part of a store a component needs, so other changes do not re-render it.", lesson: 3, group: "State" },
    // ── TypeScript ─────────────────────────────────────────────────────────
    { term: "generic", aliases: ["generics", "Generics"], full: "Generic", desc: "A type parameter. One function or type then works for many types and keeps the link between them.", lesson: 4, group: "TypeScript" },
    { term: "discriminated union", aliases: ["discriminated unions"], full: "Discriminated union", desc: "A union where every variant has a tag property with a fixed value. Checking the tag narrows the type and lets you check all cases.", lesson: 4, group: "TypeScript" },
    { term: "narrowing", aliases: ["Narrowing"], full: "Type narrowing", desc: "TypeScript makes a value's type more exact inside a branch, after a check like typeof, in or a tag comparison.", lesson: 4, group: "TypeScript" },
    { term: "unknown", full: "unknown", desc: "A safe type for a value you know nothing about. You must narrow or validate it before use. Prefer it to any.", lesson: 4, group: "TypeScript" },
    { term: "satisfies", full: "satisfies operator", desc: "Checks a value against a type but keeps the exact inferred type.", lesson: 4, group: "TypeScript" },
    { term: "Zod", full: "Zod", desc: "A TypeScript-first schema library. One schema checks data at run time and also gives you the static type with z.infer.", lesson: 4, group: "TypeScript" },
    // ── Testing and a11y ───────────────────────────────────────────────────
    { term: "Testing Library", aliases: ["React Testing Library", "RTL"], full: "Testing Library", desc: "Tests components the way users meet them: find by role, label and text, and interact with user-event.", lesson: 5, group: "Testing and accessibility" },
    { term: "MSW", full: "Mock Service Worker", desc: "Catches network requests in tests (and dev), so real components run against fake responses.", lesson: 5, group: "Testing and accessibility" },
    { term: "Playwright", full: "Playwright", desc: "A browser automation tool for end-to-end tests. Its locators wait by themselves, and its assertions wait for the page.", lesson: 5, group: "Testing and accessibility" },
    { term: "storageState", full: "Playwright storageState", desc: "Saved cookies and local storage from a login. Tests reuse it, so they start logged in without the login screen.", lesson: 5, group: "Testing and accessibility" },
    { term: "snapshot test", aliases: ["snapshot tests", "snapshot"], full: "Snapshot test", desc: "A test that saves the output and fails when it changes. Good for small stable values, noisy for big DOM trees.", lesson: 5, group: "Testing and accessibility" },
    { term: "ARIA", full: "Accessible Rich Internet Applications", desc: "Attributes that add accessibility meaning that HTML cannot express. They change what is announced, not what the element does.", lesson: 6, group: "Testing and accessibility" },
    { term: "WCAG", full: "Web Content Accessibility Guidelines", desc: "The standard for accessible web content. Level AA asks for 4.5:1 text contrast, keyboard use and more.", lesson: 6, group: "Testing and accessibility" },
    { term: "focus trap", aliases: ["Focus trap"], full: "Focus trap", desc: "Keep Tab and Shift+Tab inside a modal while it is open. The native dialog element does this for you.", lesson: 6, group: "Testing and accessibility" },
    { term: "live region", aliases: ["live regions"], full: "ARIA live region", desc: "An element whose changes a screen reader announces: role=\"status\" (polite) or role=\"alert\" (urgent).", lesson: 6, group: "Testing and accessibility" },
    { term: "accessible name", full: "Accessible name", desc: "The text a screen reader says for a control. It comes from its label, content or aria-label.", lesson: 6, group: "Testing and accessibility" },
  ],
  "fullstack-qa": [
    { term: "stacking context", aliases: ["stacking contexts"], full: "Stacking context", desc: "A group of elements that are painted together. A z-index only competes inside its own stacking context. Opacity, transform and filter can create one.", lesson: 1, group: "Frontend" },
    { term: "container query", aliases: ["container queries"], full: "Container query", desc: "A CSS rule that changes styles based on the size of a parent container, not the whole screen.", lesson: 1, group: "Frontend" },
    { term: "@layer", aliases: ["cascade layer", "cascade layers"], full: "Cascade layer", desc: "A CSS feature that sorts rules into ordered groups. A later layer wins over an earlier one, whatever the specificity.", lesson: 1, group: "Frontend" },
    { term: "tailwind-merge", full: "tailwind-merge", desc: "A small library that removes conflicting Tailwind classes, so the last one wins (for example p-2 and p-4).", lesson: 2, group: "Frontend" },
    { term: "class-variance-authority", aliases: ["cva"], full: "class-variance-authority (cva)", desc: "A small library for describing component variants (size, colour) as Tailwind class lists.", lesson: 2, group: "Frontend" },
    { term: "discriminated union", aliases: ["discriminated unions"], full: "Discriminated union", desc: "A union of object types that share one field (the tag) with a different literal value in each. Checking the tag narrows the type.", lesson: 3, group: "Frontend" },
    { term: "satisfies", full: "satisfies", desc: "A TypeScript operator that checks a value against a type but keeps the value's own, more exact type.", lesson: 3, group: "Frontend" },
    { term: "Server Component", aliases: ["Server Components"], full: "Server Component", desc: "A React component that runs only on the server. It can read data directly and sends no JavaScript to the browser.", lesson: 5, group: "Frontend" },
    { term: "Server Action", aliases: ["Server Actions"], full: "Server Action", desc: "A function marked to run on the server that a form or button can call. Treat it like a public API endpoint.", lesson: 5, group: "Frontend" },
    { term: "use cache", full: "use cache", desc: "The Next.js 16 directive that opts a function or component into caching.", lesson: 5, group: "Frontend" },
    { term: "proxy.ts", full: "proxy.ts", desc: "The Next.js 16 file that replaces middleware.ts. It runs before a request reaches a route.", lesson: 5, group: "Frontend" },
    { term: "event loop", full: "Event loop", desc: "The part of Node.js (and browsers) that picks up finished work and runs its callbacks one at a time.", lesson: 6, group: "Backend" },
    { term: "backpressure", full: "Backpressure", desc: "A slow reader telling a fast writer to wait, so memory does not fill up. Streams do this for you.", lesson: 6, group: "Backend" },
    { term: "graceful shutdown", full: "Graceful shutdown", desc: "Stopping a server by finishing current requests and closing connections before the process exits.", lesson: 6, group: "Backend" },
    { term: "ObjectId", full: "ObjectId", desc: "MongoDB's default _id: a 12-byte value that includes a timestamp.", lesson: 7, group: "Data" },
    { term: "aggregation pipeline", full: "Aggregation pipeline", desc: "A MongoDB query made of ordered stages ($match, $group, $lookup…) where each stage feeds the next.", lesson: 7, group: "Data" },
    { term: "replica set", full: "Replica set", desc: "A group of MongoDB servers holding the same data. One is the primary; the others copy it and can take over.", lesson: 7, group: "Data" },
    { term: "shard key", full: "Shard key", desc: "The field MongoDB uses to decide which shard stores a document. A poor key makes one shard too busy.", lesson: 7, group: "Data" },
    { term: "driver adapter", aliases: ["driver adapters"], full: "Driver adapter", desc: "In Prisma 7, a small package that connects Prisma Client to a database driver such as pg.", lesson: 8, group: "Data" },
    { term: "shadow database", full: "Shadow database", desc: "A temporary database that Prisma Migrate uses to check that your migrations match your schema.", lesson: 8, group: "Data" },
    { term: "N+1", aliases: ["N+1 problem"], full: "N+1 problem", desc: "One query to load a list, then one more query for each row. It is slow. Fix it by loading related data together.", lesson: 8, group: "Data" },
    { term: "session variables", aliases: ["X-Hasura-User-Id"], full: "Session variables", desc: "Values like X-Hasura-User-Id that Hasura reads from the user's token and uses in permission rules.", lesson: 9, group: "Data" },
    { term: "remote schema", aliases: ["remote schemas"], full: "Remote schema", desc: "Another GraphQL API that Hasura joins into its own, so clients see one schema.", lesson: 9, group: "Data" },
    { term: "event trigger", aliases: ["event triggers"], full: "Event trigger", desc: "A Hasura feature that calls a webhook when a row is inserted, updated or deleted. Delivery is at-least-once.", lesson: 9, group: "Data" },
    { term: "context window", full: "Context window", desc: "The maximum amount of text (in tokens) a model can look at in one request.", lesson: 10, group: "AI" },
    { term: "RAG", aliases: ["retrieval-augmented generation"], full: "Retrieval-augmented generation", desc: "Finding relevant documents first, then giving them to the model with the question so the answer uses your data.", lesson: 10, group: "AI" },
    { term: "embedding", aliases: ["embeddings"], full: "Embedding", desc: "A list of numbers that represents the meaning of a text, so similar texts are close together.", lesson: 10, group: "AI" },
    { term: "hallucination", aliases: ["hallucinations"], full: "Hallucination", desc: "When a model states something false with confidence.", lesson: 10, group: "AI" },
    { term: "agent harness", aliases: ["harness"], full: "Harness", desc: "The code around a model that runs its loop: calling tools, managing context, permissions and memory. (Not the same as an evaluation harness, which only tests models.)", lesson: 10, group: "AI" },
    { term: "MCP", aliases: ["Model Context Protocol"], full: "Model Context Protocol", desc: "An open standard for letting AI applications connect to tools and data through servers.", lesson: 10, group: "AI" },
    { term: "prompt injection", full: "Prompt injection", desc: "Hidden instructions in untrusted text that try to make a model ignore its rules or misuse its tools.", lesson: 10, group: "AI" },
    { term: "streamText", full: "streamText", desc: "The AI SDK function that calls a model and returns its answer piece by piece as it is produced.", lesson: 11, group: "AI" },
    { term: "tool calling", aliases: ["function calling"], full: "Tool calling", desc: "A model asking your code to run a function with given arguments, then using the result in its answer.", lesson: 11, group: "AI" },
    { term: "typo tolerance", full: "Typo tolerance", desc: "A search engine finding results even when the query has small spelling mistakes.", lesson: 12, group: "Search and analytics" },
    { term: "tenant token", aliases: ["tenant tokens"], full: "Tenant token", desc: "A Meilisearch token that carries search rules (like a filter) so each user can only see their own documents.", lesson: 12, group: "Search and analytics" },
    { term: "distinct_id", full: "distinct_id", desc: "The ID Mixpanel uses to say which user an event belongs to.", lesson: 12, group: "Search and analytics" },
    { term: "funnel", aliases: ["funnels"], full: "Funnel", desc: "A report that shows how many users complete each step of a flow, like sign-up, and where they drop off.", lesson: 12, group: "Search and analytics" },
    { term: "staleTime", full: "staleTime", desc: "In TanStack Query, how long fetched data counts as fresh before it is fetched again.", lesson: 13, group: "Libraries" },
    { term: "idempotency key", aliases: ["idempotency keys"], full: "Idempotency key", desc: "A unique value sent with a request so repeating it does not repeat the action, such as a second payment.", lesson: 13, group: "Libraries" },
    { term: "STAR", aliases: ["STAR method"], full: "STAR method", desc: "Situation, Task, Action, Result: a simple way to structure a story in an interview.", lesson: 14, group: "Experience" },
  ],
};
