import type { Lesson } from "./lessons";

/**
 * Accent colour for every /system-design page (headings, links, bold text, code, tooltips,
 * diagrams). "orange" is the default for this series; set it to "sky" to fall back to the
 * site-wide sky blue. Nothing else needs to change — see the accent rules in globals.css.
 */
export const SD_ACCENT: "orange" | "sky" = "orange";

export const SD_SERIES = {
  slug: "system-design",
  title: "System Design, From First Principles",
  tagline:
    "From \"what happens when you press Enter\" to designing a chat system for millions — networking, scaling, caching, databases, queues, reliability, security and real case studies, one post at a time. Every short form is explained on hover, and every idea gets a diagram.",
  started: "2026",
  accent: SD_ACCENT,
};

/** The series is split into parts, like chapters of a book. Lessons are grouped by number. */
export type SdPart = { number: number; title: string; blurb: string; from: number; to: number };

export const SD_PARTS: SdPart[] = [
  { number: 1, title: "Foundations Before System Design", blurb: "How the internet, HTTP, the OS and SQL actually work — the ground everything else stands on.", from: 1, to: 5 },
  { number: 2, title: "System Design Core Concepts", blurb: "Requirements, scaling, latency, availability and the maths you do on the back of an envelope.", from: 6, to: 10 },
  { number: 3, title: "The Building Blocks", blurb: "Load balancers, proxies, CDNs, caches, object storage, queues and search — the Lego bricks of every design.", from: 11, to: 19 },
  { number: 4, title: "Databases & Data at Scale", blurb: "SQL vs NoSQL, transactions, indexes, replication, sharding, CAP and consistency.", from: 20, to: 29 },
  { number: 5, title: "APIs & Communication", blurb: "REST, gRPC, GraphQL, real-time connections, and the API habits that keep clients safe.", from: 30, to: 34 },
  { number: 6, title: "Async & Event-Driven Systems", blurb: "Queues, pub/sub, Kafka, delivery guarantees, background jobs and events.", from: 35, to: 39 },
  { number: 7, title: "Reliability & Resilience", blurb: "Redundancy, retries, circuit breakers, rate limits, load shedding and disaster recovery.", from: 40, to: 45 },
  { number: 8, title: "Observability", blurb: "Logs, metrics, traces, SLOs, alerting and blameless postmortems.", from: 46, to: 48 },
  { number: 9, title: "Security for System Designers", blurb: "Authentication, OAuth, encryption, secrets and the OWASP Top 10.", from: 49, to: 52 },
  { number: 10, title: "Architecture & Deployment", blurb: "Monoliths, microservices, containers, Kubernetes, the cloud and shipping safely.", from: 53, to: 58 },
  { number: 11, title: "Design It Yourself: Case Studies", blurb: "A repeatable framework, then URL shorteners, rate limiters, notifications, chat and news feeds.", from: 59, to: 65 },
  { number: 12, title: "Wrap-Up & Reference", blurb: "The conclusion, a glossary of every short form, the full architecture in one picture, and a cheat sheet.", from: 66, to: 69 },
];

/** A lesson as listed in the series, plus the part it belongs to. */
export type SdLesson = Lesson & {
  part: number;
  tags: string[];
  level?: string;
};

export const partOf = (n: number) => SD_PARTS.find((p) => n >= p.from && n <= p.to)!;

export const SD_LESSONS: SdLesson[] = [
  {
    number: 1,
    slug: "lesson-1",
    title: "What Happens When You Type a URL and Press Enter?",
    summary:
      "The one second between pressing Enter and seeing a page hides a DNS lookup, a trip through a dozen routers, two handshakes and a server doing real work. Every later lesson zooms into one part of that journey.",
    readTime: "10 min",
    published: true,
    part: partOf(1).number,
    tags: ["networking", "dns", "basics"],
    level: "beginner",
  },
  {
    number: 2,
    slug: "lesson-2",
    title: "TCP vs UDP: How Data Actually Travels",
    summary:
      "The internet loses, duplicates and reorders packets. TCP promises every byte in order and pays for it in round trips; UDP just sends and lets the app cope. How each works, and how QUIC takes the best of both.",
    readTime: "8 min",
    published: true,
    part: partOf(2).number,
    tags: ["networking", "tcp", "udp"],
    level: "beginner",
  },
  {
    number: 3,
    slug: "lesson-3",
    title: "HTTP & HTTPS Explained: Methods, Status Codes and TLS",
    summary:
      "HTTP is the shared language of the web: a method and URL in, a status code and body out. HTTPS wraps it in TLS so nobody on the path can read or change it. Methods, idempotency, status codes, HTTP/1.1 vs 2 vs 3, and the TLS handshake.",
    readTime: "12 min",
    published: true,
    part: partOf(3).number,
    tags: ["http", "tls", "web"],
    level: "beginner",
  },
  {
    number: 4,
    slug: "lesson-4",
    title: "Processes, Threads & Concurrency for Backend Engineers",
    summary:
      "Most backend work is waiting. How one server juggles thousands of requests — processes, threads, event loops and lightweight threads — and the race conditions, deadlocks and pool limits that appear the moment it does.",
    readTime: "12 min",
    published: true,
    part: partOf(4).number,
    tags: ["os", "concurrency"],
    level: "beginner",
  },
  {
    number: 5,
    slug: "lesson-5",
    title: "SQL Basics Every System Designer Needs",
    summary:
      "Before sharding, replicas or NoSQL, learn to use one relational database well. Tables and keys, the queries you will write every day, indexes and EXPLAIN, the N+1 trap, transactions, and the connection limit that takes databases down.",
    readTime: "10 min",
    published: true,
    part: partOf(5).number,
    tags: ["sql", "database", "basics"],
    level: "beginner",
  },
  {
    number: 6,
    slug: "lesson-6",
    title: "What Is System Design? Start With Requirements",
    summary:
      "Two teams build the same app; one collapses on launch day. The difference is not coding skill but system design — and good design always starts with requirements you can measure.",
    readTime: "8 min",
    published: true,
    part: partOf(6).number,
    tags: ["system-design", "requirements"],
    level: "beginner",
  },
  {
    number: 7,
    slug: "lesson-7",
    title: "Vertical vs Horizontal Scaling (and Why Stateless Wins)",
    summary:
      "Bigger server or more servers? Vertical scaling is simple but hits a ceiling; horizontal scaling is nearly unlimited, but only once your app forgets everything between requests. Why stateless wins, and where state should live instead.",
    readTime: "8 min",
    published: true,
    part: partOf(7).number,
    tags: ["scalability"],
    level: "beginner",
  },
  {
    number: 8,
    slug: "lesson-8",
    title: "Latency, Throughput & Why p99 Matters",
    summary:
      "An 80 ms average can hide a checkout that freezes for five seconds. Latency, throughput and Little's Law, why queues explode near full utilisation, and why at scale the p99 becomes what most users feel.",
    readTime: "8 min",
    published: true,
    part: partOf(8).number,
    tags: ["performance", "latency"],
    level: "beginner",
  },
  {
    number: 9,
    slug: "lesson-9",
    title: "Availability and \"The Nines\" Explained",
    summary:
      "“Five nines” is 26 seconds of downtime a month. What the nines really mean, why chained dependencies multiply away your availability while redundancy multiplies it back, and why fast recovery is often the cheapest nine you can buy.",
    readTime: "8 min",
    published: true,
    part: partOf(9).number,
    tags: ["availability", "reliability"],
    level: "beginner",
  },
  {
    number: 10,
    slug: "lesson-10",
    title: "Back-of-the-Envelope Estimation, Step by Step",
    summary:
      "Five minutes of rough maths tells you whether you need one database or fifty. The numbers worth memorising, a seven-step recipe, and a full worked estimate for a photo-sharing app — with a calculator to try your own.",
    readTime: "12 min",
    published: true,
    part: partOf(10).number,
    tags: ["estimation", "interview"],
    level: "beginner",
  },
  {
    number: 11,
    slug: "lesson-11",
    title: "Anatomy of a Request: From Browser to Database",
    summary:
      "A system-design diagram looks like a wall of boxes. Follow one request — “show me my order history” — through DNS, CDN, load balancer, gateway, app servers, cache, database and queues, and learn why each box exists.",
    readTime: "8 min",
    published: true,
    part: partOf(11).number,
    tags: ["architecture", "dns"],
    level: "beginner",
  },
  {
    number: 12,
    slug: "lesson-12",
    title: "Load Balancers: L4 vs L7 and Balancing Algorithms",
    summary:
      "One address, many servers, and one of them just crashed at 2 AM. How load balancers spread traffic, L4 vs L7, the balancing algorithms and when each wins, and why a “deep” health check can take everything down at once.",
    readTime: "10 min",
    published: true,
    part: partOf(12).number,
    tags: ["load-balancer", "scalability"],
    level: "beginner",
  },
  {
    number: 13,
    slug: "lesson-13",
    title: "Reverse Proxy vs API Gateway",
    summary:
      "Reverse proxy, load balancer and API gateway get used interchangeably — NGINX is called all three. What each one is actually for, where authentication and rate limiting belong, the Backend-for-Frontend pattern, and when a gateway is overkill.",
    readTime: "8 min",
    published: true,
    part: partOf(13).number,
    tags: ["proxy", "api-gateway", "nginx"],
    level: "beginner",
  },
  {
    number: 14,
    slug: "lesson-14",
    title: "How CDNs Make the Web Fast",
    summary:
      "Your servers are in Mumbai and a user in São Paulo waits three seconds. How CDNs copy content to edges near every user, how HTTP headers control what gets cached, and how to update files that live on hundreds of servers.",
    readTime: "8 min",
    published: true,
    part: partOf(14).number,
    tags: ["cdn", "performance"],
    level: "beginner",
  },
  {
    number: 15,
    slug: "lesson-15",
    title: "Caching Part 1: Where to Cache and Why",
    summary:
      "Why ask the database the same question 10,000 times a second? What caches are, why they work so well, every layer you can cache at — browser to buffer pool — what to cache, and how Redis and Memcached compare.",
    readTime: "10 min",
    published: true,
    part: partOf(15).number,
    tags: ["caching", "redis"],
    level: "beginner",
  },
  {
    number: 16,
    slug: "lesson-16",
    title: "Caching Part 2: Strategies, Eviction and Invalidation",
    summary:
      "Adding a cache is easy; keeping it correct is hard. The six read/write strategies, why you delete rather than update on write, eviction policies you can try by hand, invalidation per data type, and the five ways caches cause outages.",
    readTime: "12 min",
    published: true,
    part: partOf(16).number,
    tags: ["caching", "redis"],
    level: "intermediate",
  },
  {
    number: 17,
    slug: "lesson-17",
    title: "Object Storage: How S3-Style Storage Works",
    summary:
      "Images saved to a server's disk vanish when you add a second server. How S3-style object storage keeps files safe at any scale, why uploads should skip your servers entirely, and what belongs in the database instead.",
    readTime: "7 min",
    published: true,
    part: partOf(17).number,
    tags: ["storage", "s3"],
    level: "beginner",
  },
  {
    number: 18,
    slug: "lesson-18",
    title: "Message Queues: A Gentle Introduction",
    summary:
      "Placing an order shouldn't wait on the email provider — or fail because SMS is down. How message queues let you do the essential work now and everything else reliably a moment later, with acks, retries, dead-letter queues and back pressure.",
    readTime: "7 min",
    published: true,
    part: partOf(18).number,
    tags: ["queues", "async"],
    level: "beginner",
  },
  {
    number: 19,
    slug: "lesson-19",
    title: "How Search Works: The Inverted Index",
    summary:
      "LIKE '%running shoes%' scans every row and still misses “running shoe”. How the inverted index flips documents into term → document lists, how analysis makes search forgiving, how BM25 ranks results, and how search scales and stays in sync.",
    readTime: "8 min",
    published: true,
    part: partOf(19).number,
    tags: ["search", "elasticsearch"],
    level: "intermediate",
  },
  {
    number: 20,
    slug: "lesson-20",
    title: "SQL vs NoSQL: Picking the Right Data Model",
    summary:
      "“SQL or NoSQL?” is the wrong question; the right one is “what shape is my data, and how will I read and write it?” The relational model and the four NoSQL families — key-value, document, wide-column and graph — what each is good at, the myths to drop, and a sensible default.",
    readTime: "12 min",
    published: true,
    part: partOf(20).number,
    tags: ["database", "nosql"],
    level: "intermediate",
  },
  {
    number: 21,
    slug: "lesson-21",
    title: "ACID Transactions & Isolation Levels",
    summary:
      "Two people book the last seat; a transfer crashes halfway. What ACID really promises, the write-ahead log behind durability, the five anomalies isolation levels do (and don't) prevent, and the practical fixes for real race conditions.",
    readTime: "12 min",
    published: true,
    part: partOf(21).number,
    tags: ["database", "transactions"],
    level: "intermediate",
  },
  {
    number: 22,
    slug: "lesson-22",
    title: "Database Indexing: B-Trees and LSM-Trees",
    summary:
      "Why an index turns 812 ms into 0.09 ms, and why it slows every write. How B-trees keep sorted pages updated in place, how LSM-trees append and compact for huge write rates, and how to design indexes from real queries.",
    readTime: "12 min",
    published: true,
    part: partOf(22).number,
    tags: ["database", "indexing"],
    level: "intermediate",
  },
  {
    number: 23,
    slug: "lesson-23",
    title: "Normalization vs Denormalization",
    summary:
      "Store each fact once and writes stay correct; copy facts on purpose and reads get fast. Normal forms in plain English, the anomalies they prevent, the denormalisation toolkit, and how to keep copies in sync.",
    readTime: "7 min",
    published: true,
    part: partOf(23).number,
    tags: ["database", "schema"],
    level: "beginner",
  },
  {
    number: 24,
    slug: "lesson-24",
    title: "Database Replication: Leader, Follower and Beyond",
    summary:
      "One database server will eventually die, drown in reads, or be too far from your users. How leader-follower replication works, what replication lag does to real users, why failover is so hard, and how multi-leader and quorum systems handle conflicts.",
    readTime: "12 min",
    published: true,
    part: partOf(24).number,
    tags: ["database", "replication"],
    level: "intermediate",
  },
  {
    number: 25,
    slug: "lesson-25",
    title: "Sharding: Splitting Data Across Machines",
    summary:
      "Indexes tuned, biggest server bought, replicas added — and the primary still drowns in writes. How sharding splits one dataset across machines, the four strategies, how to pick a shard key, and the hard problems it creates.",
    readTime: "12 min",
    published: true,
    part: partOf(25).number,
    tags: ["database", "sharding"],
    level: "intermediate",
  },
  {
    number: 26,
    slug: "lesson-26",
    title: "Consistent Hashing, Visually Explained",
    summary:
      "Add a fifth cache server to hash(key) % 4 and 80% of your keys move — the hit ratio collapses and the database falls over. How the hash ring moves only ~1/N of keys, why virtual nodes even out the load, and the alternatives.",
    readTime: "10 min",
    published: true,
    part: partOf(26).number,
    tags: ["hashing", "distributed-systems"],
    level: "intermediate",
  },
  {
    number: 27,
    slug: "lesson-27",
    title: "CAP Theorem & PACELC Without the Confusion",
    summary:
      "“MongoDB is CP, Cassandra is AP, pick two of three” — mostly misleading. What CAP really says about network partitions, why “CA” isn't a real option, and PACELC: the latency-vs-consistency trade you pay every day, even when nothing is broken.",
    readTime: "10 min",
    published: true,
    part: partOf(27).number,
    tags: ["cap", "distributed-systems"],
    level: "intermediate",
  },
  {
    number: 28,
    slug: "lesson-28",
    title: "Consistency Models: Strong, Eventual and In Between",
    summary:
      "“Eventually consistent” can mean your own comment vanishes on refresh. Consistency is a spectrum, not a switch: linearizable, causal, session guarantees and eventual — what each promises, how conflicts get merged, and why clocks can't be trusted.",
    readTime: "10 min",
    published: true,
    part: partOf(28).number,
    tags: ["consistency", "distributed-systems"],
    level: "intermediate",
  },
  {
    number: 29,
    slug: "lesson-29",
    title: "How to Choose a Database for Your System",
    summary:
      "Hundreds of databases all claim to be fast and scalable. A practical seven-step process: the questions to ask, a sensible default, the signals that justify something else, prototyping with real load, and migrating safely when you got it wrong.",
    readTime: "8 min",
    published: true,
    part: partOf(29).number,
    tags: ["database", "trade-offs"],
    level: "intermediate",
  },
  {
    number: 30,
    slug: "lesson-30",
    title: "REST API Design Best Practices",
    summary:
      "An API is a contract other teams depend on for years. How to design REST APIs that are predictable: nouns and HTTP methods, honest status codes, one error shape, filtering and pagination, free HTTP features, security basics and OpenAPI.",
    readTime: "12 min",
    published: true,
    part: partOf(30).number,
    tags: ["api", "rest"],
    level: "beginner",
  },
  {
    number: 31,
    slug: "lesson-31",
    title: "gRPC & Protocol Buffers for Beginners",
    summary:
      "Forty internal services, dozens of calls per page, JSON everywhere and contracts in a stale wiki. How gRPC and Protocol Buffers give services fast, typed, streaming calls — and the schema-evolution and load-balancing rules you must follow.",
    readTime: "10 min",
    published: true,
    part: partOf(31).number,
    tags: ["api", "grpc"],
    level: "intermediate",
  },
  {
    number: 32,
    slug: "lesson-32",
    title: "GraphQL vs REST: When to Use Which",
    summary:
      "Six REST calls to draw one profile screen, and most of the data thrown away. How GraphQL lets clients ask for exactly what they need in one request, what that costs the server — N+1, caching, expensive queries — and when to pick REST, GraphQL or gRPC.",
    readTime: "8 min",
    published: true,
    part: partOf(32).number,
    tags: ["api", "graphql"],
    level: "intermediate",
  },
  {
    number: 33,
    slug: "lesson-33",
    title: "Real-Time Apps: Polling, WebSockets and SSE",
    summary:
      "HTTP only lets the client ask. For “new message”, “rider is nearby” or an AI answer streaming in, the server has to push. Short polling, long polling, Server-Sent Events and WebSockets compared — and how to scale millions of open connections.",
    readTime: "10 min",
    published: true,
    part: partOf(33).number,
    tags: ["real-time", "websockets"],
    level: "intermediate",
  },
  {
    number: 34,
    slug: "lesson-34",
    title: "Idempotency, Pagination & API Versioning",
    summary:
      "A retried payment that charges twice, a list endpoint that loads three million rows, a renamed field that crashes every old app. Idempotency keys, cursor pagination and careful versioning — the unglamorous details that separate a demo API from a production one.",
    readTime: "10 min",
    published: true,
    part: partOf(34).number,
    tags: ["api", "reliability"],
    level: "intermediate",
  },
  {
    number: 35,
    slug: "lesson-35",
    title: "Queues vs Pub/Sub",
    summary:
      "“One of you handles this” or “all of you get a copy”? Mix them up and orders go unpacked, or customers get five emails. Queues vs pub/sub, how real systems combine both, push vs pull, per-key ordering, and delete vs keep.",
    readTime: "8 min",
    published: true,
    part: partOf(35).number,
    tags: ["messaging", "pub-sub"],
    level: "intermediate",
  },
  {
    number: 36,
    slug: "lesson-36",
    title: "Apache Kafka Fundamentals",
    summary:
      "Thirty services all need each other's data, and the data team wants to replay last week. How Kafka's simple idea — a partitioned, replicated, append-only log — became the backbone of event streaming: topics, keys, offsets, consumer groups, retention and compaction.",
    readTime: "12 min",
    published: true,
    part: partOf(36).number,
    tags: ["kafka", "streaming"],
    level: "intermediate",
  },
  {
    number: 37,
    slug: "lesson-37",
    title: "At-Most-Once, At-Least-Once, Exactly-Once",
    summary:
      "Acknowledge too early and a crash loses the payment; acknowledge too late and it charges twice. At-most-once, at-least-once and why true exactly-once is impossible — plus idempotent consumers, Kafka's exactly-once and the transactional outbox.",
    readTime: "8 min",
    published: true,
    part: partOf(37).number,
    tags: ["messaging", "kafka"],
    level: "intermediate",
  },
  {
    number: 38,
    slug: "lesson-38",
    title: "Background Jobs, Retries & Dead-Letter Queues",
    summary:
      "Background jobs are easy to start and surprisingly easy to get wrong: poison jobs, retry storms, cron that runs twice, deploys that kill half-done work. How to design jobs, retry only what can succeed, and route what can't to a dead-letter queue you actually watch.",
    readTime: "10 min",
    published: true,
    part: partOf(38).number,
    tags: ["async", "workers"],
    level: "intermediate",
  },
  {
    number: 39,
    slug: "lesson-39",
    title: "Event-Driven Architecture for Beginners",
    summary:
      "The order service calls seven other services and fails whenever any of them does. Event-driven architecture flips it: announce what happened and let whoever cares react. Events vs commands, the four patterns called “event-driven”, choreography vs orchestration, and sagas.",
    readTime: "8 min",
    published: true,
    part: partOf(39).number,
    tags: ["architecture", "events"],
    level: "intermediate",
  },
  {
    number: 40,
    slug: "lesson-40",
    title: "Single Points of Failure, Redundancy & Failover",
    summary:
      "The site went down, and the culprit was none of the redundant boxes on the diagram but the one NAT gateway, the one DNS provider, or an expired certificate. How to hunt single points of failure, shrink blast radius, add redundancy that works, and fail over without split brain.",
    readTime: "10 min",
    published: true,
    part: partOf(40).number,
    tags: ["reliability", "availability"],
    level: "intermediate",
  },
  {
    number: 41,
    slug: "lesson-41",
    title: "Timeouts, Retries & Backoff with Jitter",
    summary:
      "One slow dependency with no timeout, plus clients that retry instantly, can take down an entire site. How to set timeouts from real latency, propagate deadlines, retry only what's safe, avoid retry amplification, and why backoff needs jitter.",
    readTime: "10 min",
    published: true,
    part: partOf(41).number,
    tags: ["reliability", "resilience"],
    level: "intermediate",
  },
  {
    number: 42,
    slug: "lesson-42",
    title: "Circuit Breaker & Bulkhead Patterns",
    summary:
      "Timeouts limit how long you wait per call, but not how often you keep calling a service you already know is dead. How circuit breakers fail fast and test for recovery, how bulkheads stop one dependency exhausting everything, and how to design honest fallbacks.",
    readTime: "8 min",
    published: true,
    part: partOf(42).number,
    tags: ["resilience", "patterns"],
    level: "intermediate",
  },
  {
    number: 43,
    slug: "lesson-43",
    title: "Rate Limiting Algorithms Explained",
    summary:
      "One buggy script calling 5,000 times a second can hurt every customer. How rate limiting protects your system and keeps usage fair: the five classic algorithms — with a simulator you can drive — distributed limiting in Redis, and how to tell clients to slow down.",
    readTime: "12 min",
    published: true,
    part: partOf(43).number,
    tags: ["rate-limiting", "api"],
    level: "intermediate",
  },
  {
    number: 44,
    slug: "lesson-44",
    title: "Graceful Degradation & Load Shedding",
    summary:
      "At 5× your planned peak, trying to serve everyone means serving no one. How to fail partially and on purpose: rank features and switch off the optional ones, reject excess work early and cheaply, shed by priority, and use waiting rooms for spikes you can see coming.",
    readTime: "8 min",
    published: true,
    part: partOf(44).number,
    tags: ["resilience"],
    level: "intermediate",
  },
  {
    number: 45,
    slug: "lesson-45",
    title: "Backups & Disaster Recovery: RPO vs RTO",
    summary:
      "Replication faithfully copies a mistaken DELETE, ransomware or silent corruption to every replica in milliseconds. Why backups are a different thing, how RPO and RTO drive every decision, point-in-time recovery, the 3-2-1 rule, the four DR strategies, and why an untested backup is only a hope.",
    readTime: "8 min",
    published: true,
    part: partOf(45).number,
    tags: ["reliability", "dr"],
    level: "intermediate",
  },
  {
    number: 46,
    slug: "lesson-46",
    title: "Logs, Metrics & Traces: The Three Pillars",
    summary:
      "“Checkout took 20 seconds and failed” — but checkout touches eleven components. How logs, metrics and traces each answer a different question, how to instrument with OpenTelemetry, and how linking them takes you from “something's wrong” to “here's why” in minutes.",
    readTime: "10 min",
    published: true,
    part: partOf(46).number,
    tags: ["observability", "opentelemetry"],
    level: "intermediate",
  },
  {
    number: 47,
    slug: "lesson-47",
    title: "SLI, SLO, SLA & Error Budgets",
    summary:
      "Product wants to ship daily; operations wants fewer changes; nobody agrees what “reliable enough” means. SLIs, SLOs and SLAs turn it into one number, and error budgets turn that number into a simple rule for when to move fast and when to slow down.",
    readTime: "10 min",
    published: true,
    part: partOf(47).number,
    tags: ["sre", "reliability"],
    level: "intermediate",
  },
  {
    number: 48,
    slug: "lesson-48",
    title: "Monitoring, Alerting & Blameless Postmortems",
    summary:
      "Sixty alerts a week, fifty-five that don't matter — so the real one gets snoozed and customers can't pay for two hours. How to build dashboards and alerts people trust, run incidents with clear roles, and write blameless postmortems that actually make the system better.",
    readTime: "8 min",
    published: true,
    part: partOf(48).number,
    tags: ["sre", "monitoring"],
    level: "intermediate",
  },
  {
    number: 49,
    slug: "lesson-49",
    title: "Authentication vs Authorization: Sessions, Cookies & JWT",
    summary:
      "Every endpoint checked “is the user logged in?” — and changing one number in the URL showed another customer's invoice. Authentication vs authorization, storing passwords, MFA and passkeys, sessions vs JWTs (with a live token to tamper with), and RBAC, ABAC and ReBAC.",
    readTime: "12 min",
    published: true,
    part: partOf(49).number,
    tags: ["security", "auth", "jwt"],
    level: "intermediate",
  },
  {
    number: 50,
    slug: "lesson-50",
    title: "OAuth 2.0 & OpenID Connect Explained",
    summary:
      "Apps used to ask for your Google password to print your photos. How OAuth 2.0 hands out limited, expiring, revocable “valet keys” instead, how OpenID Connect adds login on top, and the flows and checks that keep it secure.",
    readTime: "12 min",
    published: true,
    part: partOf(50).number,
    tags: ["security", "oauth"],
    level: "intermediate",
  },
  {
    number: 51,
    slug: "lesson-51",
    title: "Encryption & Secrets Management",
    summary:
      "Unencrypted traffic “inside our network”, an unencrypted backup in a public bucket, a database password pushed to GitHub. Where to encrypt in transit and at rest, who holds the keys, how envelope encryption and KMS work, end-to-end encryption, and how to store, deliver and rotate secrets.",
    readTime: "10 min",
    published: true,
    part: partOf(51).number,
    tags: ["security", "tls"],
    level: "intermediate",
  },
  {
    number: 52,
    slug: "lesson-52",
    title: "OWASP Top 10 for Backend Developers",
    summary:
      "Most breaches don't need a genius hacker — just a missing ownership check, a string-glued SQL query or a default password. The OWASP Top 10 explained for backend developers, with the attack, the fix and a real incident for each, plus the API-specific risks.",
    readTime: "10 min",
    published: true,
    part: partOf(52).number,
    tags: ["security", "owasp"],
    level: "intermediate",
  },
  {
    number: 53,
    slug: "lesson-53",
    title: "Monolith vs Microservices: An Honest Comparison",
    summary:
      "A five-person startup with 14 services, and a 300-engineer company with one two-hour deploy — both chose wrong. Monoliths, microservices and the modular monolith in between, how to find boundaries, how to migrate with the strangler fig, and the signals that tell you which fits.",
    readTime: "12 min",
    published: true,
    part: partOf(53).number,
    tags: ["architecture", "microservices"],
    level: "intermediate",
  },
  {
    number: 54,
    slug: "lesson-54",
    title: "Service Discovery: How Services Find Each Other",
    summary:
      "A hard-coded IP address is out of date within minutes once containers auto-scale and redeploy all day. How services find the current, healthy addresses of each other: registries, health checks, client-side vs server-side discovery, DNS, service meshes, and shutting down without dropping requests.",
    readTime: "7 min",
    published: true,
    part: partOf(54).number,
    tags: ["microservices"],
    level: "intermediate",
  },
  {
    number: 55,
    slug: "lesson-55",
    title: "Docker & Containers for Beginners",
    summary:
      "“It works on my machine” ends here. What containers really are (and aren't), images, layers and registries, a production-grade multi-stage Dockerfile, running and composing containers locally, tags vs digests, and the security basics.",
    readTime: "10 min",
    published: true,
    part: partOf(55).number,
    tags: ["docker", "containers"],
    level: "beginner",
  },
  {
    number: 56,
    slug: "lesson-56",
    title: "Kubernetes Core Concepts",
    summary:
      "Running 300 containers across 40 machines by hand doesn't work. How Kubernetes turns “what I want” into “what's running”: the control plane and nodes, the reconciliation loop, pods, deployments, services and ingress, health probes, resources and autoscaling — and whether you need it at all.",
    readTime: "12 min",
    published: true,
    part: partOf(56).number,
    tags: ["kubernetes", "devops"],
    level: "intermediate",
  },
  {
    number: 57,
    slug: "lesson-57",
    title: "Cloud Fundamentals: Regions, AZs & Serverless",
    summary:
      "Servers that once took months to order now take minutes — but the cloud has its own concepts, failure modes and surprise bills. Regions and availability zones, IaaS to SaaS, serverless and cold starts, the shared responsibility model, cost, and infrastructure as code.",
    readTime: "8 min",
    published: true,
    part: partOf(57).number,
    tags: ["cloud", "aws"],
    level: "beginner",
  },
  {
    number: 58,
    slug: "lesson-58",
    title: "CI/CD & Deployment Strategies: Blue-Green and Canary",
    summary:
      "Friday-evening deploys that need three people and a prayer are optional. CI that catches problems before merge, continuous delivery vs deployment, rolling, blue-green and canary releases — with a simulator — feature flags, zero-downtime database migrations and the DORA metrics.",
    readTime: "10 min",
    published: true,
    part: partOf(58).number,
    tags: ["devops", "deployment"],
    level: "intermediate",
  },
  {
    number: 59,
    slug: "lesson-59",
    title: "A 5-Step Framework for Any System Design Problem",
    summary:
      "A blank whiteboard and “design Instagram” is terrifying without a plan. A five-step framework that works for any system design problem — requirements, estimation, API and data model, high-level design, deep dives — with a worked Pastebin example and the common mistakes to avoid.",
    readTime: "10 min",
    published: true,
    part: partOf(59).number,
    tags: ["interview", "framework"],
    level: "intermediate",
  },
  {
    number: 60,
    slug: "lesson-60",
    title: "Design a URL Shortener",
    summary:
      "The classic first case study, end to end. Requirements and estimates, the API and data model, how to generate short codes (hashing vs counters vs Snowflake IDs — with a live base62 encoder), a read path that serves 20,000 redirects a second, 301 vs 302, and click analytics.",
    readTime: "15 min",
    published: true,
    part: partOf(60).number,
    tags: ["case-study"],
    level: "intermediate",
  },
  {
    number: 61,
    slug: "lesson-61",
    title: "Design a Rate Limiter",
    summary:
      "Designing the rate limiter itself, as a real service: 100,000 requests a second, many rules per request, sub-millisecond checks. Requirements, estimates, a rule model, a Redis-backed gateway design, atomic Lua checks, hot keys, fail-open vs fail-closed, and multi-region.",
    readTime: "15 min",
    published: true,
    part: partOf(61).number,
    tags: ["case-study"],
    level: "intermediate",
  },
  {
    number: 62,
    slug: "lesson-62",
    title: "Design a Notification System",
    summary:
      "OTPs that must arrive in seconds, order updates, and a marketing blast to 20 million users in ten minutes — through push, SMS, email and in-app. A full design: API, preferences and templates, priority queues, channel workers, provider fallback, deduplication, rate limits and delivery tracking.",
    readTime: "15 min",
    published: true,
    part: partOf(62).number,
    tags: ["case-study"],
    level: "intermediate",
  },
  {
    number: 63,
    slug: "lesson-63",
    title: "Design a Chat System",
    summary:
      "Fifty million daily users, ten million online at once, 70,000 messages a second, one-to-one and groups, sent/delivered/read ticks and nothing ever lost. A full chat system design: WebSocket gateways, per-conversation sequence numbers, a wide-column message store, presence, offline push and sync.",
    readTime: "18 min",
    published: true,
    part: partOf(63).number,
    tags: ["case-study", "websockets"],
    level: "advanced",
  },
  {
    number: 64,
    slug: "lesson-64",
    title: "Design a News Feed",
    summary:
      "A hundred million users opening a feed ten times a day, and one celebrity post that must reach fifty million followers. A full news-feed design: fan-out on write vs on read, the hybrid that handles celebrities, feed caches, hydration, ranking, pagination and counters.",
    readTime: "18 min",
    published: true,
    part: partOf(64).number,
    tags: ["case-study"],
    level: "advanced",
  },
  {
    number: 65,
    slug: "lesson-65",
    title: "What I Learned From Big Tech Engineering Blogs",
    summary:
      "Interview designs are clean; real systems are messy, migrated and patched for years. How to read engineering blogs and postmortems so you actually learn from them, the ten lessons that keep repeating across big-tech stories, and a reading list to keep going.",
    readTime: "10 min",
    published: true,
    part: partOf(65).number,
    tags: ["case-study", "learning"],
    level: "all",
  },
  {
    number: 66,
    slug: "lesson-66",
    title: "System Design Series: The Conclusion",
    summary:
      "Sixty-five posts ago we started with a URL and the Enter key. The whole journey on one page, the twenty principles that matter most, a checklist you can use for any design, how every piece fits together, and what to do next.",
    readTime: "10 min",
    published: true,
    part: partOf(66).number,
    tags: ["system-design", "summary"],
    level: "all",
  },
  {
    number: 67,
    slug: "glossary",
    title: "System Design Glossary: Every Short Form Explained",
    summary:
      "Every short form in the series — TLS, CDN, ACID, CAP, SLO, JWT, K8s and 300 more — in plain English, with what it does and an everyday example.",
    readTime: "30 min",
    published: true,
    part: partOf(67).number,
    tags: ["system-design", "glossary", "reference"],
    level: "all",
  },
  {
    number: 68,
    slug: "lesson-68",
    title: "The Complete System Design Architecture",
    summary:
      "Every building block from the series, assembled into one reference architecture — clients, edge, entry, services, cache, databases, object storage, search, async, analytics, external services and the cross-cutting layer — with four request flows traced through it and how it grows from one user to millions.",
    readTime: "20 min",
    published: true,
    part: partOf(68).number,
    tags: ["system-design", "architecture", "reference"],
    level: "all",
  },
  {
    number: 69,
    slug: "lesson-69",
    title: "System Design in 15 Minutes: Recap & Cheat Sheet",
    summary:
      "The whole series, compressed for the night before an interview: the framework, the numbers, the formulas, the nines, a one-screen recap of every part, “if you need X, use Y”, the big trade-offs, common problems and their fixes, and rapid-fire questions to test yourself.",
    readTime: "15 min",
    published: true,
    part: partOf(69).number,
    tags: ["system-design", "cheat-sheet", "interview", "reference"],
    level: "all",
  },
];

/** Lesson 67 is the glossary, which has its own page. Everything else is /system-design/lesson-N. */
export function sdLessonHref(lesson: Lesson): string {
  return `/${SD_SERIES.slug}/${lesson.slug}`;
}
